Repository GouvernementFR/dsfr, pull requests merged in 2021-11, with the labels that each got.

#90 fix: readme et contributing [DS-2078]
  CONTRIBUTING.md
  README.md
Labels: documentation

#92 fix(modal): focus trap avec iframe [DS-2127]
  src/component/modal/example/index.ejs
  src/component/modal/example/sample/body/iframe.ejs
  src/component/modal/script/modal/focus-trap.js
Labels: correctif

#87 fix(footer): met a jour le wording du copyright [DS-2064]
  src/component/display/example/index.ejs
  src/component/footer/example/sample/footer-minimal.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/example/sample/footer-total.ejs
Labels: correctif

#101 fix(consent): ajout d'id aux services
  src/component/consent/example/sample/modal/body.ejs
Labels: correctif

#80 fix(modale): corrige la hauteur de la modale sur desktop [DS-2076]
  src/component/modal/style/_module.scss
Labels: correctif

#43 feat(upload): ajout du composant upload [DS-1918]
  src/component/main.scss
  src/component/upload/.package.yml
  src/component/upload/example/index.ejs
  src/component/upload/example/sample/upload-multiple.ejs
  src/component/upload/example/sample/upload.ejs
  src/component/upload/index.scss
  src/component/upload/main.scss
  src/component/upload/style/_module.scss
  src/component/upload/template/ejs/upload.ejs
Labels: ajout

#102 fix(upload): disabled input-upload & curseur pointeur
  src/core/style/action/setting/_elements.scss
Labels: correctif

#60 feat(core): ajout du reset de hr [DS-1882]
  src/core/.package.yml
  src/core/example/display/index.ejs
  src/core/example/display/sample/hr.ejs
  src/core/example/index.ejs
  src/core/example/reset/index.ejs
  src/core/example/reset/sample/hr.ejs
  src/core/example/spacing/sample/spacing.ejs
  src/core/style/_scheme.scss
  src/core/style/display/_module.scss
  src/core/style/display/_scheme.scss
  src/core/style/display/module/_hr.scss
  src/core/style/display/scheme/_hr.scss
  src/core/style/reset/_module.scss
  src/core/style/reset/_scheme.scss
  src/core/style/reset/_setting.scss
  src/core/style/reset/_tool.scss
  src/core/style/reset/module/_hr.scss
  src/core/style/reset/scheme/_hr.scss
  src/core/style/reset/tool/_hr.scss
  src/core/style/typography/_setting.scss
  src/core/style/typography/setting/_spacing.scss
  src/core/style/typography/setting/_text.scss
  src/core/style/typography/tool/_build.scss
  src/core/style/typography/tool/_styles.scss
Labels: ajout

#73 fix: margin bottom <p> et <hx> des composants [DS-2013]
  src/component/alert/style/_module.scss
  src/component/breadcrumb/style/_module.scss
  src/component/callout/style/_module.scss
  src/component/card/style/_module.scss
  src/component/consent/example/sample/modal/body.ejs
  src/component/consent/style/module/_banner.scss
  src/component/consent/style/module/_placeholder.scss
  src/component/consent/template/ejs/banner.ejs
  src/component/consent/template/ejs/manager.ejs
  src/component/consent/template/ejs/placeholder.ejs
  src/component/content/style/_module.scss
  src/component/follow/style/_module.scss
  src/component/follow/template/ejs/follow.ejs
  src/component/follow/template/ejs/newsletter.ejs
  src/component/follow/template/ejs/socials.ejs
  src/component/header/style/_module.scss
  src/component/header/style/module/_brand.scss
  src/component/link/style/tool/_build.scss
  src/component/navigation/style/module/_mega-menu.scss
  src/component/navigation/style/module/_nav.scss
  src/component/quote/style/_module.scss
  src/component/share/example/index.ejs
  src/component/share/example/sample/share-default.ejs
  src/component/share/style/_module.scss
  src/component/share/template/ejs/share.ejs
  src/component/sidemenu/style/_module.scss
  src/component/sidemenu/style/module/_link.scss
  src/component/sidemenu/style/module/_title.scss
  src/component/summary/style/_module.scss
  src/component/tab/style/_module.scss
  src/component/table/style/_module.scss
  src/component/tile/style/_module.scss
  src/core/style/typography/tool/_styles.scss
Labels: évolution

#68 fix(navigation): nav-link hover sur a et button uniquement [DS-1982]
  src/component/navigation/style/module/_mega-menu.scss
Labels: correctif

#93 feat(icon): ajout icon logout [DS-2128]
  src/core/example/icon/index.ejs
  src/core/icon/svg/logout-box-r-fill.svg
  src/core/icon/svg/logout-box-r-line.svg
Labels: ajout

#94 refactor(ejs): ajoute des exemples disabled et checked
  src/component/checkbox/example/sample/checkboxes.ejs
  src/component/checkbox/template/ejs/checkbox.ejs
  src/component/radio/example/sample/radios.ejs
  src/component/radio/template/ejs/radio.ejs
  src/component/share/example/sample/share-default.ejs
  src/component/toggle/example/index.ejs
  src/component/toggle/template/ejs/toggle.ejs
Labels: évolution

#105 fix(navigation): espacement catégories mobile
  src/component/navigation/style/module/_mega-menu.scss
Labels: correctif

#88 fix(cards): corrige taille image mode horizontal [DS-1986]
  src/component/card/style/_module.scss
Labels: correctif

#109 feat(display): Ajout icones illustratives & thème systeme [DS-2103]
  src/component/content/template/ejs/media-img.ejs
  src/component/display/example/sample/body.ejs
  src/component/form/example/sample/fieldset.ejs
  src/component/legacy.scss
  src/component/radio/example/sample/radio-rich.ejs
  src/component/radio/style/_scheme.scss
  src/component/radio/style/module/_rich.scss
  src/component/radio/template/ejs/radio.ejs
  src/core/asset/artwork/dark.svg
  src/core/asset/artwork/light.svg
  src/core/asset/artwork/system.svg
  src/core/index.js
  src/core/main.js
  src/core/script/inject/inject-svg-selector.js
  src/core/script/inject/inject-svg.js
  src/core/template/ejs/media/img.ejs
  src/core/template/ejs/media/responsive-img.ejs
Labels: évolution

#112 fix: ejs corrections multiples [DS-1854]
  src/component/accordion/template/ejs/accordion.ejs
  src/component/button/example/index.ejs
  src/component/button/example/sample/button-default.ejs
  src/component/button/example/sample/buttons-group.ejs
  src/component/button/template/ejs/button.ejs
  src/component/card/example/sample/card-default.ejs
  src/component/checkbox/example/sample/checkboxes.ejs
  src/component/checkbox/style/_scheme.scss
  src/component/checkbox/template/ejs/checkbox-group.ejs
  src/component/content/example/sample/media-vid-default.ejs
  src/component/follow/example/sample/data.ejs
  src/component/follow/example/sample/newsletter-only-form.ejs
  src/component/follow/example/sample/socials-newsletter-form.ejs
  src/component/follow/template/ejs/follow.ejs
  src/component/follow/template/ejs/newsletter.ejs
  src/component/follow/template/ejs/socials.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/example/sample/footer-total.ejs
  src/component/footer/style/_module.scss
  src/component/footer/style/module/_content.scss
  src/component/footer/template/ejs/footer.ejs
  src/component/footer/template/ejs/partners.ejs
  src/component/form/style/_module.scss
  src/component/form/style/_scheme.scss
  src/component/form/style/_tool.scss
  src/component/input/example/index.ejs
  src/component/input/example/sample/input-text.ejs
  src/component/input/style/_scheme.scss
  src/component/input/template/ejs/input.ejs
  src/component/modal/style/_module.scss
  src/component/pagination/template/ejs/item.ejs
  src/component/radio/style/scheme/_md.scss
  src/component/radio/style/scheme/_rich.scss
  src/component/radio/style/scheme/_sm.scss
  src/component/select/style/_scheme.scss
  src/component/summary/example/index.ejs
  src/component/summary/example/sample/summary.ejs
  src/component/summary/style/_module.scss
  src/component/summary/template/ejs/summary.ejs
  src/component/tab/example/sample/tabs-default.ejs
  src/component/toggle/template/ejs/toggle.ejs
  src/core/example/media/sample/vid.ejs
  src/core/script/inject/inject-svg.js
  src/core/style/selector/_tool.scss
  src/core/style/selector/tool/_autofill.scss
  src/core/template/ejs/includes.ejs
  src/core/template/ejs/media/img.ejs
  src/scheme/script/scheme/scheme.js
  tool/example/example.ejs
  tool/example/wrapper.ejs
  yarn.lock
Labels: correctif

#113 feat(example): ajoute un bouton fixe pour les parametre d'affichage [DS-2166]
  src/component/display/example/index.ejs
  tool/build/example.js
  tool/example/example.ejs
  tool/example/parameter.ejs
  tool/example/style.css.ejs
Labels: ajout

#118 fix(display): ajoute des attributs d'accessibilité sur les svg [DS-2103]
  src/core/script/api/utilities/attribute.js
  src/core/script/inject/inject-svg.js
Labels: correctif

#121 fix(card): ajoute un modifier d'accentuation [DS-2164]
  src/component/card/example/index.ejs
  src/component/card/example/sample/vertical-cards.ejs
  src/component/card/style/_scheme.scss
  src/component/card/template/ejs/card.ejs
Labels: correctif

#120 fix: correctifs ejs form [DS-1854]
  src/component/content/example/sample/media-img.ejs
  src/component/form/template/ejs/fieldset.ejs
  src/component/input/example/index.ejs
  src/component/input/example/sample/input-button.ejs
  src/component/radio/example/sample/radio-rich.ejs
  src/component/radio/example/sample/radio.ejs
  src/component/select/example/index.ejs
  src/component/select/example/sample/select.ejs
  src/component/toggle/template/ejs/toggle.ejs
  src/component/upload/template/ejs/upload.ejs
Labels: correctif

#119 fix(display): corrige bouton d'affichage et bug a la selection du mode [DS-2147] [DS-2176]
  src/component/display/example/index.ejs
  src/component/display/example/layout-snippet-only.ejs
  tool/build/example.js
  tool/example/parameter.ejs
  tool/example/style.css.ejs
Labels: correctif

#115 fix(search): met a jour le reset des boutons et champs de saisie pour Safari [DS-2168]
  src/core/style/reset/module/_input.scss
  src/core/style/reset/tool/_button.scss
Labels: correctif

#124 fix: pa11y hide disable elements & fix lint dependance [DS-2177]
  package.json
  tool/test/pa11y.js
  yarn.lock
Labels: correctif

#123 fix(card): met a jour le modifier d'accent [DS-2164]
  src/component/card/example/index.ejs
  src/component/card/style/_scheme.scss
Labels: correctif

#122 fix(radio): bordure sur la classe radio-rich__img
  src/component/radio/style/module/_rich.scss
  src/component/radio/style/scheme/_rich.scss
  src/component/radio/template/ejs/radio.ejs
Labels: correctif

#125 fix(callout): accentuation du background [DS-2181]
  src/component/callout/style/_scheme.scss
Labels: correctif

#131 fix(footer): couleur catégorie menu [DS-1436]
  src/component/footer/style/_scheme.scss
Labels: correctif

#127 fix(inject-svg): ajoute une methode globale sur l'api pour definir legacy [DS-2103]
  src/component/button/style/_scheme.scss
  src/component/display/script/display/display-selector.js
  src/component/display/script/display/display.js
  src/component/header/style/_scheme.scss
  src/component/share/style/_module.scss
  src/component/sidemenu/style/_scheme.scss
  src/component/table/style/_scheme.scss
  src/component/table/style/module/_variants.scss
  src/core/legacy.js
  src/core/script/api/api.js
  src/core/script/api/register/instance.js
  src/core/script/api/state.js
  src/core/script/inject/inject-svg.js
  src/core/style/color/tool/_element.scss
Labels: correctif

#143 Feat(yarn) : Mise à jour des dépendances de développement majeures et mineures [DS-2196]
  .husky/commit-msg
  package.json
  tool/test/test.js
  yarn.lock
Labels: dependencies

#141 fix(upload): ajout aria described [DS-2213]
  src/component/upload/template/ejs/upload.ejs
Labels: correctif

#146 feat(sidemenu): ajoute le chevron sur le aria-expanded [DS-2229]
  src/component/sidemenu/example/index.ejs
  src/component/sidemenu/example/sample/sidemenu.ejs
  src/component/sidemenu/style/_module.scss
  src/component/sidemenu/style/_scheme.scss
  src/component/sidemenu/style/module/_action.scss
  src/component/sidemenu/style/module/_link.scss
  src/component/sidemenu/style/module/_list.scss
  src/component/sidemenu/template/ejs/list.ejs
  src/component/sidemenu/template/ejs/menu.ejs
Labels: ajout

#149 feat(core): ajout icone filter [DS-2228]
  src/core/example/icon/index.ejs
  src/core/icon/svg/filter-fill.svg
  src/core/icon/svg/filter-line.svg
Labels: évolution

#148 feat(core): ajout meta theme-color dans favicon [DS-2231]
  README.md
  src/core/template/ejs/favicon/favicon.ejs
Labels: évolution

#147 fix(card-tile): met a jour les noms de class d'accentuation [DS-2227]
  src/component/card/example/index.ejs
  src/component/card/style/_scheme.scss
  src/component/tile/example/index.ejs
  src/component/tile/style/_scheme.scss
Labels: correctif

#144 fix(header): corrections css pour IE, valeur initial [DS-1088]
  src/component/header/legacy.scss
  src/component/header/style/_legacy.scss
Labels: correctif

#151 fix(sidemenu): correction du hover des liens [DS-2230]
  src/component/sidemenu/style/module/_action.scss
Labels: correctif
