Repository GouvernementFR/dsfr, pull requests merged in 2021-12, with the labels that each got.

#162 fix(card): bordure extérieure sur les cartes [DS-2295]
  src/component/card/style/_scheme.scss
  src/core/style/color/setting/_box-shadows.scss
Labels: correctif

#89 fix(tab): corrige le scroll horizontal [DS-2074]
  src/component/tab/style/_module.scss
Labels: correctif

#142 feat(tab): ajout modifieur viewport-width [DS-2075]
  src/component/tab/example/index.ejs
  src/component/tab/example/sample/tabs-default.ejs
  src/component/tab/style/_module.scss
  src/component/tab/template/ejs/tabs.ejs
Labels: correctif, évolution

#167 fix(tile): background tile [DS-2329]
  src/component/tile/style/_scheme.scss
Labels: correctif

#154 fix(legacy): ie listes et marges [DS-1088]
  src/component/accordion/legacy.scss
  src/component/accordion/style/_legacy.scss
  src/component/alert/legacy.scss
  src/component/alert/style/_legacy.scss
  src/component/breadcrumb/legacy.scss
  src/component/breadcrumb/style/_legacy.scss
  src/component/button/legacy.scss
  src/component/button/style/_legacy.scss
  src/component/callout/legacy.scss
  src/component/callout/style/_legacy.scss
  src/component/card/legacy.scss
  src/component/card/style/_legacy.scss
  src/component/follow/legacy.scss
  src/component/follow/style/_legacy.scss
  src/component/footer/legacy.scss
  src/component/footer/style/_legacy.scss
  src/component/footer/style/_scheme.scss
  src/component/form/legacy.scss
  src/component/form/style/_legacy.scss
  src/component/link/legacy.scss
  src/component/link/style/_legacy.scss
  src/component/navigation/legacy.scss
  src/component/navigation/style/_legacy.scss
  src/component/pagination/legacy.scss
  src/component/pagination/style/_legacy.scss
  src/component/quote/legacy.scss
  src/component/quote/style/_legacy.scss
  src/component/share/legacy.scss
  src/component/share/style/_legacy.scss
  src/component/sidemenu/style/_legacy.scss
  src/component/sidemenu/style/module/_variants.scss
  src/component/tab/legacy.scss
  src/component/tab/style/_legacy.scss
  src/component/table/legacy.scss
  src/component/table/style/_legacy.scss
  src/component/tile/legacy.scss
  src/component/tile/style/_legacy.scss
  src/component/tile/style/_module.scss
  tool/build/styles.js
Labels: correctif

#159 feat(tab): ajout de l'ombre au scroll & recentrage des boutons [DS-2073] [DS-2042]
  src/component/modal/script/modal/modal-body.js
  src/component/modal/script/modal/modal-emission.js
  src/component/modal/script/modal/modal.js
  src/component/tab/index.js
  src/component/tab/index.scss
  src/component/tab/main.js
  src/component/tab/script/tab/tab-button.js
  src/component/tab/script/tab/tab-selector.js
  src/component/tab/script/tab/tabs-group.js
  src/component/tab/script/tab/tabs-list.js
  src/component/tab/style/_module.scss
  src/component/tab/style/_tool.scss
  src/component/tab/style/module/_shadow.scss
  src/component/tab/style/tool/_shadow.scss
  src/core/style/spacing/setting/_z-index.scss
Labels: évolution
