Repository GouvernementFR/dsfr, pull requests merged in 2022-11, with the labels that each got.

#439 fix(form): ajout du css deprecated legacy
  src/component/form/legacy.scss
Labels: correctif

#448 fix(scheme): correctifs de l'API JS de couleur [DS-2907]
  module/color/variable/_decisions.scss
  src/core/script/api/utilities/colors/colors.js
  src/scheme/script/scheme/scheme.js
Labels: correctif

#449 fix(download): titre des cartes en h3 [DS-2904]
  src/component/download/template/ejs/download.ejs
Labels: correctif

#451 fix(core, download): correction du enlarge link [DS-2777]
  src/component/download/style/_tool.scss
  src/component/link/style/tool/_icon.scss
  src/component/link/style/tool/_nest.scss
  src/pattern/address/i18n/fr.yml
Labels: correctif

#452 fix(transcription): titre du contenu (a11y) [DS-2906]
  src/component/transcription/example/sample/transcription-default.ejs
  src/component/transcription/i18n/fr.yml
  src/component/transcription/template/ejs/transcription.ejs
Labels: correctif

#453 fix(tag): déplacement du focus sur les tags supprimables [DS-2905]
  src/component/tag/example/index.ejs
  src/component/tag/example/sample/tag-dismissable.ejs
  src/component/tag/example/sample/tag-dismissible.ejs
  src/component/tag/index.js
  src/component/tag/main.js
  src/component/tag/script/tag/tag-dismissible.js
  src/component/tag/script/tag/tag-event.js
  src/component/tag/script/tag/tag-selector.js
  src/component/tag/template/ejs/tag.ejs
  src/core/script/api/modules/register/instance.js
  src/core/script/api/utilities/dom/actions.js
  src/core/script/api/utilities/dom/index.js
Labels: correctif

#436 feat(pagination): border active sur version constrasté [DS-2717]
  module/media-query/_index.scss
  module/media-query/mixin/_contrast.scss
  src/component/pagination/legacy.scss
  src/component/pagination/main.scss
  src/component/pagination/style/_contrast-scheme.scss
  src/component/pagination/style/_contrast.scss
Labels: correctif

#454 fix(display): correctif duplication du sélecteur de langue [DS-2908]
  src/component/header/script/header/header-links.js
Labels: correctif

#466 fix(transcription): correction du titre h1 de la modale caché en mode accordéon
  src/component/consent/example/index.ejs
  src/component/content/example/index.ejs
  src/component/content/example/sample/media-default.ejs
  src/component/content/example/sample/media-img.ejs
  src/component/content/example/sample/media-svg.ejs
  src/component/content/example/sample/media-vid-default.ejs
  src/component/transcription/i18n/fr.yml
  src/component/transcription/style/_module.scss
Labels: correctif

#465 fix(footer): correction sur le séparateur bleu du pied de page
  src/component/footer/style/module/_top.scss
Labels: correctif

#463 fix(core): ouverture des disclosures à partir des ancres, état disabled désactive disclosure [DS-2805, DS-2533]
  src/component/accordion/script/accordion/accordions-group.js
  src/component/header/example/sample/header.ejs
  src/component/header/script/header/header-modal.js
  src/component/header/template/ejs/tools.ejs
  src/component/modal/script/modal/modal.js
  src/component/navigation/script/navigation/navigation.js
  src/component/password/script/password/password-toggle.js
  src/component/sidemenu/script/sidemenu/sidemenu-list.js
  src/component/skiplink/example/prepend.ejs
  src/component/tab/script/tab/tab-button.js
  src/component/tab/script/tab/tabs-group.js
  src/component/tag/script/tag/tag-dismissible.js
  src/core/script/action/toggle/toggle.js
  src/core/script/api/engine.js
  src/core/script/api/modules/hash/hash.js
  src/core/script/api/modules/register/instance.js
  src/core/script/api/modules/scroll/scroll-locker.js
  src/core/script/collapse/collapse-button.js
  src/core/script/collapse/collapse.js
  src/core/script/disclosure/disclosure-button.js
  src/core/script/disclosure/disclosure-type.js
  src/core/script/disclosure/disclosure.js
  src/core/script/disclosure/disclosures-group.js
  src/core/style/display/module/_no-scroll.scss
Labels: correctif, ajout

#467 feat(deps): mise à jour des dependances npm [DS-2936]
  .gitignore
  CONTRIBUTING.md
  package.json
  yarn.lock
Labels: dependencies

#473 fix(scheme): ajout du mode sombre de la scrollbar du navigateur (#407)
  src/scheme/script/scheme/scheme-boot.js
  src/scheme/script/scheme/scheme.js
Labels: ajout

#475 fix(input): date picker correction placement icone calendrier [DS-2547]
  src/component/input/input-base/style/_module.scss
Labels: correctif

#477 fix(core): correction du curseur des textarea [DS-2952]
  src/core/style/action/setting/_elements.scss
Labels: correctif

#480 fix(tag): correction régression lien tag [DS-2975]
  src/component/tag/style/_legacy.scss
  src/component/tag/style/_scheme.scss
  src/component/tag/style/module/_group.scss
Labels: correctif
