Repository GouvernementFR/dsfr, pull requests merged in 2022-07, with the labels that each got.

#365 feat(i18n): système i18n globalisé
  i18n/fr.yml
  src/component/accordion/.package.yml
  src/component/badge/.package.yml
  src/component/button/.package.yml
  src/component/connect/.package.yml
  src/component/connect/example/sample/connect-agent.ejs
  src/component/connect/example/sample/connect-default.ejs
  src/component/connect/example/sample/connect-plus.ejs
  src/component/connect/i18n/de.yml
  src/component/connect/i18n/en.yml
  src/component/connect/i18n/es.yml
  src/component/connect/i18n/fr.yml
  src/component/connect/template/ejs/connect.ejs
  src/component/legacy.scss
  src/component/main.scss
  src/component/pagination/.package.yml
  src/component/tab/.package.yml
  src/component/tag/.package.yml
  tool/build/build.js
  tool/build/example.js
  tool/build/standalone.js
  tool/classes/config/config.js
  tool/classes/i18n/aggregated-i18n.js
  tool/classes/i18n/i18n-package.js
  tool/classes/i18n/i18n.js
  tool/classes/md/readme.js
  tool/classes/utility/object-utility.js
  tool/example/decorator.ejs
  tool/generate/font-subset.js
  tool/generate/markdown.js
Labels: évolution

#373 fix(stepper): correction barre d'étape masquée sur Firefox [DS-2760]
  src/component/stepper/style/_module.scss
  src/component/stepper/style/_scheme.scss
Labels: correctif

#353 fix(footer, header): généralisation de l'attribut 'title' du lien retour/accueil du logo [DS-2682]
  module/color/mixin/_element.scss
  src/component/footer/example/index.ejs
  src/component/footer/example/sample/footer.ejs
  src/component/footer/style/_scheme.scss
  src/component/footer/style/module/_default.scss
  src/component/footer/template/ejs/brand.ejs
  src/component/footer/template/ejs/partners.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/template/ejs/brand.ejs
  src/component/logo/template/ejs/logo.ejs
  src/core/style/action/module/_enlarge-link.scss
  src/core/style/action/tool/_hover.scss
  tool/example/decorator.ejs
Labels: correctif, évolution

#359 feat(translate) : Ajout du sélecteur de langue [DS-2017]
  src/component/button/style/module/_group.scss
  src/component/button/style/tool/_group.scss
  src/component/button/template/ejs/button.ejs
  src/component/card/style/module/_default.scss
  src/component/connect/style/module/_default.scss
  src/component/consent/style/module/_banner.scss
  src/component/header/.package.yml
  src/component/header/deprecated/style/_module.scss
  src/component/header/example/index.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/script/header/header-links.js
  src/component/header/style/_legacy.scss
  src/component/header/style/_scheme.scss
  src/component/header/style/module/_default.scss
  src/component/header/style/module/_links.scss
  src/component/header/style/module/_nav.scss
  src/component/header/template/ejs/tools.ejs
  src/component/legacy.scss
  src/component/main.scss
  src/component/navigation/script/navigation/navigation-item.js
  src/component/navigation/style/_legacy.scss
  src/component/navigation/style/module/_default.scss
  src/component/navigation/style/module/_mega-menu.scss
  src/component/navigation/style/module/_menu.scss
  src/component/sidemenu/style/module/_default.scss
  src/component/translate/.package.yml
  src/component/translate/example/index.ejs
  src/component/translate/example/sample/get-translations.ejs
  src/component/translate/example/sample/translate-big.ejs
  src/component/translate/example/sample/translate-default.ejs
  src/component/translate/i18n/fr.yml
  src/component/translate/index.scss
  src/component/translate/legacy.scss
  src/component/translate/main.scss
  src/component/translate/style/_legacy.scss
  src/component/translate/style/_module.scss
  src/component/translate/style/_scheme.scss
  src/component/translate/template/ejs/languages.ejs
  src/component/translate/template/ejs/translate.ejs
  src/core/style/action/module/_focus.scss
Labels: ajout

#376 fix(global): correction des erreurs pa11y
  src/component/display/example/index.ejs
  src/component/translate/example/index.ejs
Labels: correctif

#371 feat(page-error): ajoute les modeles de page erreur 404 [DS-1941]
  module/color/variable/_decisions.scss
  src/component/accordion/legacy.scss
  src/core/asset/artwork/background/ovoid.svg
  src/core/asset/artwork/technical-error.svg
  src/core/style/artwork/_scheme.scss
  src/core/template/ejs/artwork/artwork.ejs
  src/page/.folder.yml
  src/page/api.js
  src/page/main.js
  src/page/main.scss
  src/page/response/.folder.yml
  src/page/response/example/sample/default.ejs
  src/page/response/i18n/fr.yml
  src/page/response/not-found/.package.yml
  src/page/response/not-found/example/complete/index.ejs
  src/page/response/not-found/example/contact/index.ejs
  src/page/response/not-found/example/default/index.ejs
  src/page/response/not-found/example/default/sample/default.ejs
  src/page/response/not-found/example/index.ejs
  src/page/response/not-found/example/layout.ejs
  src/page/response/not-found/example/search/index.ejs
  src/page/response/not-found/i18n/fr.yml
  src/page/response/template/ejs/response.ejs
  src/utility/colors/_setting.scss
  tool/classes/i18n/i18n.js
Labels: ajout

#330 feat(server): Ajout page erreur serveur [DS-2662]
  i18n/fr.yml
  module/color/mixin/_element.scss
  module/elevation/mixin/_define.scss
  src/component/form/template/ejs/fieldset.ejs
  src/component/select/example/sample/select.ejs
  src/page/response/example/sample/default.ejs
  src/page/response/i18n/fr.yml
  src/page/response/template/ejs/response.ejs
  src/page/response/unavailable/.package.yml
  src/page/response/unavailable/asset/broken-connection.png
  src/page/response/unavailable/asset/broken-connection.svg
  src/page/response/unavailable/asset/marianne.png
  src/page/response/unavailable/i18n/fr.yml
  src/page/response/unavailable/standalone/example/index.ejs
  src/page/response/unavailable/standalone/main.scss
  src/page/response/unavailable/standalone/style/_module.scss
  src/page/response/unavailable/standalone/style/_scheme.scss
  src/pattern/.folder.yml
  tool/build/example.js
  tool/classes/utility/ArrayUtility.js
Labels: ajout

#374 fix(card): correction aspect ratio par défaut [DS-2729]
  src/component/card/style/module/_header.scss
Labels: correctif

#379 fix(not-found): ajuste la template not-found [DS-1941]
  module/elevation/mixin/_define.scss
  src/page/response/example/sample/default.ejs
  src/page/response/template/ejs/response.ejs
  src/page/response/unavailable/standalone/style/_scheme.scss
  tool/classes/i18n/i18n-locale.js
  tool/classes/i18n/i18n.js
Labels: correctif

#378 fix(card): correction de l'aspect ratio par défaut des vidéos [DS-2729]
  src/component/card/example/index.ejs
  src/component/card/style/module/_header.scss
Labels: correctif

#380 fix(unavailable): ajout de la page d'exemple [DS-2662]
  src/component/card/style/module/_header.scss
  src/page/response/unavailable/example/index.ejs
  src/page/response/unavailable/i18n/fr.yml
  tool/build/build.js
  tool/build/standalone.js
  tool/tool.js
Labels: correctif

#381 chore(global): mis à jour des dépendances
  yarn.lock
Labels: dependencies

#361 Feature/Models-Patterns
  i18n/fr.yml
  src/component/form/style/_module.scss
  src/component/form/style/_scheme.scss
  src/component/input/template/ejs/input.ejs
  src/component/radio/i18n/fr.yml
  src/component/select/example/sample/select.ejs
  src/component/select/i18n/fr.yml
  tool/example/decorator.ejs
  tool/example/layout.ejs
Labels: ajout

#363 refactor(input): Séparation en sous composant d'input, ajout de input-email et input-tel [DS-2640] [DS-2646]
  src/component/follow/template/ejs/newsletter.ejs
  src/component/form/example/index.ejs
  src/component/input/.folder.yml
  src/component/input/example/index.ejs
  src/component/input/example/sample/input-mail.ejs
  src/component/input/example/sample/input-tel.ejs
  src/component/input/example/sample/input-text.ejs
  src/component/input/index.scss
  src/component/input/input-base/.package.yml
  src/component/input/input-base/example/index.ejs
  src/component/input/input-base/example/sample/input-button.ejs
  src/component/input/input-base/example/sample/input-date.ejs
  src/component/input/input-base/example/sample/input-number.ejs
  src/component/input/input-base/example/sample/input-password.ejs
  src/component/input/input-base/example/sample/input-search.ejs
  src/component/input/input-base/example/sample/input-text.ejs
  src/component/input/input-base/example/sample/inputs.ejs
  src/component/input/input-base/example/sample/textarea.ejs
  src/component/input/input-base/i18n/fr.yml
  src/component/input/input-base/index.scss
  src/component/input/input-base/legacy.scss
  src/component/input/input-base/main.scss
  src/component/input/input-base/style/_legacy.scss
  src/component/input/input-base/style/_module.scss
  src/component/input/input-base/style/_scheme.scss
  src/component/input/input-base/style/_setting.scss
  src/component/input/input-base/style/_tool.scss
  src/component/input/input-base/template/ejs/input-group.ejs
  src/component/input/input-base/template/ejs/input.ejs
  src/component/input/input-email/.package.yml
  src/component/input/input-email/example/index.ejs
  src/component/input/input-email/example/sample/email-default.ejs
  src/component/input/input-email/i18n/fr.yml
  src/component/input/input-email/template/ejs/email.ejs
  src/component/input/input-tel/.package.yml
  src/component/input/input-tel/example/index.ejs
  src/component/input/input-tel/example/sample/tel-default.ejs
  src/component/input/input-tel/i18n/fr.yml
  src/component/input/input-tel/template/ejs/tel.ejs
  src/component/input/legacy.scss
  src/component/input/main.scss
  src/component/legacy.scss
  src/component/main.scss
  src/component/modal/example/sample/body/form.ejs
  src/component/search/template/ejs/search.ejs
Labels: ajout

#356 feat(pattern): ajoute le modele de nom et prenom [DS-2634]
  src/component/form/template/ejs/fieldset.ejs
  src/pattern/name/.package.yml
  src/pattern/name/example/index.ejs
  src/pattern/name/example/layout.ejs
  src/pattern/name/example/sample/button-and-firstname-disabled.ejs
  src/pattern/name/example/sample/button.ejs
  src/pattern/name/example/sample/firstname-disabled.ejs
  src/pattern/name/example/sample/international-and-firstname-disabled.ejs
  src/pattern/name/example/sample/international.ejs
  src/pattern/name/example/sample/name.ejs
  src/pattern/name/example/sample/usage-name-and-firstname-disabled.ejs
  src/pattern/name/example/sample/usage-name.ejs
  src/pattern/name/i18n/fr.yml
  src/pattern/name/template/ejs/name.ejs
Labels: ajout

#391 feat(password): ajout du composant mot de passe [DS-2637]
  src/component/checkbox/example/sample/checkboxes.ejs
  src/component/checkbox/template/ejs/checkbox.ejs
  src/component/input/input-base/example/sample/inputs.ejs
  src/component/input/input-base/template/ejs/input.ejs
  src/component/legacy.scss
  src/component/main.js
  src/component/main.scss
  src/component/password/.package.yml
  src/component/password/api.js
  src/component/password/example/index.ejs
  src/component/password/example/sample/password-login.ejs
  src/component/password/example/sample/password-register.ejs
  src/component/password/example/sample/sample-description.ejs
  src/component/password/example/sample/sample-validate.ejs
  src/component/password/i18n/fr.yml
  src/component/password/index.js
  src/component/password/index.scss
  src/component/password/legacy.scss
  src/component/password/main.js
  src/component/password/main.scss
  src/component/password/script/password/password-emission.js
  src/component/password/script/password/password-input.js
  src/component/password/script/password/password-label.js
  src/component/password/script/password/password-selector.js
  src/component/password/script/password/password-toggle.js
  src/component/password/script/password/password.js
  src/component/password/style/_legacy.scss
  src/component/password/style/_module.scss
  src/component/password/style/_scheme.scss
  src/component/password/style/_setting.scss
  src/component/password/template/ejs/password.ejs
  src/core/icon/system/fr--capslock-line.svg
Labels: ajout
