Repository GouvernementFR/dsfr, pull requests merged in 2022-02, with the labels that each got.

#207 fix(core): ordre media query [DS-2381]
  src/core/main.scss
Labels: correctif

#206 fix(core): faute dans le texte alternatif [DS-2153]
  src/core/template/ejs/media/img.ejs
Labels: correctif

#204 fix(navigation, sidemenu): correction focus coupés [DS-2322][DS-2309][DS-2089]
  src/component/button/template/ejs/buttons-group.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/template/ejs/header.ejs
  src/component/header/template/ejs/menu.ejs
  src/component/header/template/ejs/navbar.ejs
  src/component/navigation/style/module/_mega-menu.scss
  src/component/navigation/template/ejs/mega-menu.ejs
  src/component/sidemenu/style/_module.scss
  src/component/sidemenu/style/module/_inner.scss
  src/component/tag/style/_legacy.scss
Labels: correctif

#210 fix(toggle): correction de l'état précoché de l'interrupteur [DS-2392]
  src/component/toggle/script/toggle/toggle-emission.js
  src/component/toggle/script/toggle/toggle-input.js
Labels: correctif

#214 fix(accordion): a11y retrait des ul li du groupe d'accordéon [DS-2348]
  src/component/accordion/template/ejs/accordions-group.ejs
Labels: correctif

#213 fix(toggle, modal): correction z-index de toggle [DS-2385]
  src/component/modal/style/_module.scss
  src/component/toggle/style/module/_toggle.scss
  src/core/style/spacing/setting/_z-index.scss
Labels: correctif

#228 feat(dependencies): mise a jour des dépendances node mineures
  package.json
  yarn.lock
Labels: dependencies

#212 feat(core): variabilisation du core [DS-2315]
  src/core/style/_setting.scss
  src/core/style/_tool.scss
  src/core/style/display/_tool.scss
  src/core/style/display/module/_ellipsis.scss
  src/core/style/display/module/_hidden.scss
  src/core/style/display/module/_hr.scss
  src/core/style/display/scheme/_hr.scss
  src/core/style/display/tool/_ellipsis.scss
  src/core/style/display/tool/_hidden.scss
  src/core/style/function/_map.scss
  src/core/style/reset/_setting.scss
  src/core/style/spacing/module/_margin.scss
  src/core/style/spacing/setting/_margin.scss
  src/core/style/spacing/tool/_margin.scss
  src/core/style/tool/_utility.scss
  src/core/style/typography/_module.scss
  src/core/style/typography/_setting.scss
  src/core/style/typography/_tool.scss
  src/core/style/typography/setting/_font-weight.scss
  src/core/style/typography/setting/_text.scss
  src/core/style/typography/setting/_title.scss
  src/core/style/typography/tool/_build-typography.scss
  src/core/style/typography/tool/_font-weight.scss
  src/core/style/typography/tool/_styles.scss
  src/core/variables.scss
Labels: évolution
