Repository GouvernementFR/dsfr, pull requests merged in 2022-10, with the labels that each got.

#406 fix(sidemenu): sidemenu disparait à l'ouverture modale FF [DS-2723]
  src/core/main.scss
  src/core/style/_outdated.scss
Labels: correctif

#405 fix(tabs): Ouverture de modal à l'intérieur d'un composant onglet [DS-2731]
  src/component/tab/style/module/_default.scss
Labels: correctif

#420 fix(tile, summary, sidemenu): niveau de titre des composants [DS-1805]
  src/component/alert/template/ejs/alert.ejs
  src/component/callout/template/ejs/callout.ejs
  src/component/card/template/ejs/content.ejs
  src/component/follow/template/ejs/newsletter.ejs
  src/component/follow/template/ejs/socials.ejs
  src/component/sidemenu/template/ejs/sidemenu.ejs
  src/component/stepper/template/ejs/stepper.ejs
  src/component/summary/template/ejs/summary.ejs
  src/component/tile/template/ejs/tile.ejs
  tool/example/parameter.ejs
Labels: correctif, évolution

#424 feat(api): ajoute la class Colors [DS-2888]
  src/core/script/api/api.js
  src/core/script/api/utilities/colors/colors.js
Labels: ajout

#427 feat(api): ajoute un event sur scheme [DS-2888]
  src/scheme/index.js
  src/scheme/script/scheme/scheme-event.js
  src/scheme/script/scheme/scheme.js
Labels: ajout

#432 fix(accordion): correction token de couleur [DS-2700]
  src/component/accordion/style/_scheme.scss
Labels: correctif

#430 fix(tag): correction tag selectionnable hover [DS-2724]
  src/component/tag/style/_scheme.scss
  src/component/tag/style/_tool.scss
Labels: correctif

#428 fix(form, upload): error & disabled [DS-2746, DS-2700]
  src/component/form/deprecated/style/_scheme.scss
  src/component/form/example/index.ejs
  src/component/form/style/_scheme.scss
  src/component/form/style/module/_fieldset.scss
  src/component/form/template/ejs/fieldset/element.ejs
  src/component/form/template/ejs/fieldset/fieldset.ejs
  src/component/upload/example/index.ejs
  src/component/upload/example/sample/upload-multiple.ejs
  src/component/upload/example/sample/upload.ejs
  src/component/upload/i18n/fr.yml
  src/component/upload/template/ejs/upload.ejs
  src/pattern/company/example/data/siret.json.ejs
Labels: correctif

#437 fix(quote): couleur du texte quote__sources [DS-2806]
  src/component/quote/style/_scheme.scss
Labels: correctif

#426 feat(nationality): pattern nationalité [DS-2658]
  src/pattern/nationality/.package.yml
  src/pattern/nationality/data/nationalities.json
  src/pattern/nationality/example/data/nationality-select-options.json.ejs
  src/pattern/nationality/example/data/nationality.json.ejs
  src/pattern/nationality/example/index.ejs
  src/pattern/nationality/example/sample/default.ejs
  src/pattern/nationality/i18n/fr.yml
Labels: ajout

#442 fix(scheme): correctif thème sombre (fix #440)
  src/scheme/script/scheme/scheme-event.js
Labels: correctif
