Repository GouvernementFR/dsfr, pull requests merged in 2022-01, with the labels that each got.

#172 fix(tab): retrait du smooth scroll [DS-2042]
  src/component/tab/style/_module.scss
Labels: correctif

#173 fix(legacy): retire les polyfills legacy du script module [DS-2304]
  src/legacy.js
  src/legacy/legacy.js
  src/legacy/main.js
Labels: correctif

#165 feat(logo): modifie l'intitulé par défaut [DS-2249]
  src/component/footer/example/index.ejs
  src/component/footer/example/sample/footer-minimal.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/example/sample/footer-total.ejs
  src/component/header/example/index.ejs
  src/component/header/template/ejs/brand.ejs
  src/component/logo/example/index.ejs
  src/component/logo/example/sample/logo.ejs
Labels: correctif

#170 fix(scheme): ajoute methode de detection du localstorage [DS-2328]
  src/component/accordion/main.js
  src/component/accordion/script/accordion/accordion-selector.js
  src/component/breadcrumb/main.js
  src/component/breadcrumb/script/breadcrumb/breadcrumb-selector.js
  src/component/button/main.js
  src/component/button/script/button/button-selector.js
  src/component/display/main.js
  src/component/display/script/display/display-selector.js
  src/component/header/main.js
  src/component/header/script/header/header-selector.js
  src/component/modal/main.js
  src/component/modal/script/modal/focus-trap.js
  src/component/modal/script/modal/modal-attribute.js
  src/component/modal/script/modal/modal-selector.js
  src/component/navigation/main.js
  src/component/navigation/script/navigation/navigation-item.js
  src/component/navigation/script/navigation/navigation-selector.js
  src/component/sidemenu/main.js
  src/component/sidemenu/script/sidemenu/sidemenu-selector.js
  src/component/tab/main.js
  src/component/tab/script/tab/tab-selector.js
  src/component/table/main.js
  src/component/table/script/table/table-emission.js
  src/component/table/script/table/table-selector.js
  src/core/legacy.js
  src/core/main.js
  src/core/script/api/api.js
  src/core/script/api/internals.js
  src/core/script/api/utilities/dom/classes.js
  src/core/script/api/utilities/dom/index.js
  src/core/script/api/utilities/dom/query-selector.js
  src/core/script/api/utilities/property/complete-assign.js
  src/core/script/api/utilities/property/index.js
  src/core/script/api/utilities/support/browser-support.js
  src/core/script/api/utilities/support/index.js
  src/scheme/main.js
  src/scheme/script/scheme/scheme-attribute.js
  src/scheme/script/scheme/scheme-emission.js
  src/scheme/script/scheme/scheme-selector.js
  src/scheme/script/scheme/scheme.js
Labels: correctif

#176 fix: retours d'accessibilité a11y [DS-2253][DS-2255][DS-2256][DS-2260][DS-2261][DS-2262][DS-2263][DS-2267][DS-2273]
  src/component/button/example/index.ejs
  src/component/consent/template/ejs/banner.ejs
  src/component/consent/template/ejs/manager.ejs
  src/component/content/example/index.ejs
  src/component/content/example/sample/media-svg.ejs
  src/component/follow/example/index.ejs
  src/component/follow/example/sample/newsletter-only-form.ejs
  src/component/follow/example/sample/socials-newsletter-form.ejs
  src/component/follow/template/ejs/socials.ejs
  src/component/form/style/_module.scss
  src/component/share/example/sample/share-default.ejs
  src/component/share/style/_module.scss
  src/component/share/template/ejs/share-link.ejs
  src/component/share/template/ejs/share.ejs
  src/core/example/media/sample/svg--illu.ejs
  src/core/example/media/sample/svg.ejs
Labels: correctif

#175 fix: commentaire des textes alternatif des images [DS-2153]
  src/component/card/example/sample/card-default.ejs
  src/component/content/example/sample/media-img.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/style/_scheme.scss
  src/component/header/example/index.ejs
  src/component/header/example/sample/header.ejs
  src/component/quote/example/sample/quote-with-image.ejs
  src/component/radio/example/sample/radio-rich.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/core/example/media/sample/img.ejs
  src/core/template/ejs/media/img.ejs
  tool/example/wrapper.ejs
Labels: correctif

#174 feat(core): Ajout des valeurs d'espacement 0.5v et 1.5v [DS-2246]
  src/core/example/spacing/sample/spacing.ejs
  src/core/style/spacing/setting/_margin.scss
  src/core/style/spacing/tool/_margin.scss
Labels: évolution

#59 feat(badge): ajout du composant badge [DS-1921]
  src/component/badge/.package.yml
  src/component/badge/example/index.ejs
  src/component/badge/example/sample/badge-default.ejs
  src/component/badge/example/sample/badge-ellipsis.ejs
  src/component/badge/example/sample/badge-sm.ejs
  src/component/badge/index.scss
  src/component/badge/legacy.scss
  src/component/badge/main.scss
  src/component/badge/style/_module.scss
  src/component/badge/style/_scheme.scss
  src/component/badge/style/_setting.scss
  src/component/badge/style/_tool.scss
  src/component/badge/template/ejs/badge.ejs
  src/component/legacy.scss
  src/component/link/style/tool/_icon.scss
  src/component/link/style/tool/_size.scss
  src/component/main.scss
  src/component/scheme.scss
  src/component/tag/template/ejs/tag.ejs
  src/core/example/icon/index.ejs
  src/core/icon/svg/flashlight-fill.svg
  src/core/icon/svg/flashlight-line.svg
  src/core/style/display/_module.scss
  src/core/style/display/module/_ellipsis.scss
  src/core/style/icon/_setting.scss
Labels: ajout

#181 fix(link, tag, pagination, share): role & aria link disabled [DS-2274]
  src/component/link/example/index.ejs
  src/component/link/template/ejs/link.ejs
  src/component/pagination/template/ejs/item.ejs
  src/component/share/template/ejs/share-link.ejs
  src/component/tag/template/ejs/tag.ejs
Labels: correctif

#184 chore(deps): mise a jour des dépendances
  package.json
  yarn.lock
Labels: évolution, dependencies

#187 fix(consent): titre bandeau en h2 [DS-2250]
  src/component/consent/template/ejs/banner.ejs
Labels: correctif

#186 fix(follow): texte d'erreur email & centrage alignement icone erreur/valid [DS-2261]
  src/component/follow/example/index.ejs
  src/component/form/style/_module.scss
Labels: correctif

#188 fix(radio): sup sub exemple [DS-2041]
  src/component/radio/example/index.ejs
Labels: correctif

#182 fix(alert): retrait attribut role='alert' et collapse [DS-2274]
  src/component/alert/example/index.ejs
  src/component/alert/example/sample/alert-dismissable.ejs
  src/component/alert/template/ejs/alert.ejs
  tool/example/wrapper.ejs
Labels: correctif

#185 fix(toggle): statut activer/desactiver a11y [DS-2272]
  src/component/main.js
  src/component/toggle/.package.yml
  src/component/toggle/api.js
  src/component/toggle/index.js
  src/component/toggle/main.js
  src/component/toggle/script/toggle/toggle-emission.js
  src/component/toggle/script/toggle/toggle-input.js
  src/component/toggle/script/toggle/toggle-selector.js
  src/component/toggle/script/toggle/toggle-status-label.js
  src/component/toggle/style/module/_toggle.scss
Labels: correctif

#189 fix(tag): sélectionnable [DS-2105]
  src/component/tag/example/index.ejs
Labels: correctif, documentation

#192 fix(toggle, modal): patch 1.3.1 - status width & modal icon aria-hidden
  src/component/modal/template/ejs/modal.ejs
  src/component/toggle/script/toggle/toggle-status-label.js
Labels: correctif

#193 fix(toggle): status width [DS-2272]
  src/component/toggle/script/toggle/toggle-status-label.js
Labels: correctif

#194 feat(alert): ajout exemple dynamique [DS-2368]
  src/component/alert/example/index.ejs
  src/component/alert/example/layout-dynamic.ejs
  src/component/alert/example/sample/alert-dismissable.ejs
  src/component/alert/template/ejs/alert.ejs
Labels: ajout

#202 fix: ordre des media query au build css [DS-2381]
  src/_media-query-order.scss
  src/component/follow/main.scss
  src/component/footer/main.scss
  src/component/header/main.scss
  src/component/header/style/_legacy.scss
  src/component/legacy.scss
  src/component/main.scss
  src/component/navigation/style/_legacy.scss
  src/component/tag/style/_legacy.scss
  src/core/style/display/tool/_hidden.scss
  src/core/style/display/tool/_sr-only.scss
  src/legacy.scss
  src/main.scss
  tool/generate/concatenate.js
Labels: correctif

#171 fix(doc): met a jour la doc des templates ejs [DS-1787]
  src/component/accordion/template/ejs/accordions-group.ejs
  src/component/alert/template/ejs/alert.ejs
  src/component/button/template/ejs/button.ejs
  src/component/button/template/ejs/buttons-group.ejs
  src/component/callout/template/ejs/callout.ejs
  src/component/card/template/ejs/card.ejs
  src/component/checkbox/template/ejs/checkbox-group.ejs
  src/component/checkbox/template/ejs/checkbox.ejs
  src/component/consent/template/ejs/banner.ejs
  src/component/consent/template/ejs/manager.ejs
  src/component/consent/template/ejs/placeholder.ejs
  src/component/follow/template/ejs/follow.ejs
  src/component/follow/template/ejs/newsletter.ejs
  src/component/follow/template/ejs/socials.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/template/ejs/bottom.ejs
  src/component/footer/template/ejs/brand.ejs
  src/component/footer/template/ejs/content.ejs
  src/component/footer/template/ejs/footer.ejs
  src/component/footer/template/ejs/partners.ejs
  src/component/footer/template/ejs/top.ejs
  src/component/form/template/ejs/fieldset.ejs
  src/component/form/template/ejs/message.ejs
  src/component/header/example/index.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/template/ejs/body.ejs
  src/component/header/template/ejs/brand.ejs
  src/component/header/template/ejs/header.ejs
  src/component/header/template/ejs/links.ejs
  src/component/header/template/ejs/menu.ejs
  src/component/header/template/ejs/navbar.ejs
  src/component/header/template/ejs/tools.ejs
  src/component/input/template/ejs/input-group.ejs
  src/component/input/template/ejs/input.ejs
  src/component/link/template/ejs/link.ejs
  src/component/logo/template/ejs/logo.ejs
  src/component/modal/template/ejs/btn.ejs
  src/component/modal/template/ejs/modal.ejs
  src/component/navigation/template/ejs/mega-menu.ejs
  src/component/navigation/template/ejs/navigation.ejs
  src/component/quote/template/ejs/quote.ejs
  src/component/radio/template/ejs/radio-group.ejs
  src/component/radio/template/ejs/radio.ejs
  src/component/search/template/ejs/search.ejs
  src/component/select/template/ejs/select-group.ejs
  src/component/select/template/ejs/select.ejs
  src/component/share/template/ejs/share-link.ejs
  src/component/sidemenu/template/ejs/link.ejs
  src/component/sidemenu/template/ejs/menu.ejs
  src/component/summary/template/ejs/list.ejs
  src/component/summary/template/ejs/summary.ejs
  src/component/tab/template/ejs/tab.ejs
  src/component/tab/template/ejs/tabs.ejs
  src/component/table/template/ejs/table.ejs
  src/component/tag/template/ejs/tag.ejs
  src/component/tile/template/ejs/tile.ejs
  src/component/toggle/template/ejs/toggle-group.ejs
  src/component/toggle/template/ejs/toggle.ejs
  src/component/upload/template/ejs/upload.ejs
  src/core/template/ejs/media/responsive-vid.ejs
Labels: correctif
