Repository GouvernementFR/dsfr, pull requests merged in 2022-06, with the labels that each got.

#332 fix(table): bug ios bordures qui n'apparaissent pas [DS-2186]
  src/component/table/style/_scheme.scss
  src/component/table/style/module/_default.scss
  src/component/table/style/module/_variants.scss
Labels: correctif

#329 fix(stepper): cache le détail de la dernière étape en css [DS-2446]
  src/component/stepper/style/_module.scss
  src/component/stepper/style/_tool.scss
Labels: correctif

#335 fix(header): correctif espacement liens rapides [DS-2680]
  src/component/header/deprecated/style/_module.scss
  src/component/header/style/module/_links.scss
Labels: correctif

#336 fix(navigation): correctif focus au clic sur les liens [DS-2677]
  src/component/navigation/script/navigation/navigation.js
  src/component/table/style/module/_variants.scss
Labels: correctif

#334 fix(icons): correctif depreciation fr-fi-checkbox-circle-line [DS-2702]
  src/utility/icons/deprecated/style/_setting.scss
Labels: correctif

#333 fix(core,link,button,tag,card): correctif icône lien extérieur [DS-2510]
  src/component/button/style/_setting.scss
  src/component/card/style/_legacy.scss
  src/component/card/style/module/_content.scss
  src/component/link/style/_setting.scss
  src/component/link/style/tool/_build.scss
  src/component/link/style/tool/_icon.scss
  src/component/tag/style/_setting.scss
  src/core/style/action/module/_link.scss
  src/core/style/action/tool/_link.scss
Labels: correctif

#331 fix(follow, share): ajout texte explicatif icones RS disponibles [DS-2598][DS-2597]
  src/component/follow/example/index.ejs
  src/component/follow/style/_module.scss
  src/component/follow/style/_tool.scss
  src/component/share/example/index.ejs
  src/component/share/style/_module.scss
  src/component/share/style/_tool.scss
Labels: documentation

#339 fix(core): suppression de l'icône lien extérieur sur une balise form [DS-2706]
  src/core/style/action/module/_link.scss
Labels: correctif

#341 fix(core): suppression de l'icône lien extérieur sur une balise form [DS-2706]
  src/component/link/style/_module.scss
  src/core/style/action/module/_link.scss
Labels: correctif

#338 fix(card): correctif des tailles fixes des cartes horizontales [DS-2707]
  src/component/card/style/module/_horizontal.scss
Labels: correctif

#344 fix(core): correction du soulignement des liens
  src/core/style/action/module/_enlarge-link.scss
  src/core/style/action/tool/_link.scss
Labels: correctif

#343 fix(core): correction du fond du svg - faux positif PA11Y
  src/core/example/media/sample/svg.ejs
Labels: correctif

#345 feat(core): mise à disposition de state et stage dans l'api js
  src/core/script/api/internals.js
Labels: évolution

#346 fix(core): correction de l'épaisseur du soulignement des liens
  src/core/style/action/tool/_link.scss
Labels: correctif

#357 feat(global): multiplication des pages d'exemple et internationalisation [DS-1381]
  i18n/fr.yml
  src/component/accordion/example/imbrication/index.ejs
  src/component/accordion/example/imbrication/sample/accordion-in-accordion.ejs
  src/component/accordion/example/imbrication/sample/accordions-group-in-accordions-group.ejs
  src/component/accordion/example/imbrication/sample/tabs-in-accordion.ejs
  src/component/accordion/example/index.ejs
  src/component/accordion/example/sample/accordion-in-accordion.ejs
  src/component/accordion/example/sample/tabs-in-accordion.ejs
  src/component/accordion/i18n/fr.yml
  src/component/connect/.package.yml
  src/component/connect/content.json
  src/component/connect/example/index.ejs
  src/component/connect/example/sample/connect-default.ejs
  src/component/connect/example/sample/connect-plus.ejs
  src/component/connect/i18n/de.yml
  src/component/connect/i18n/en.yml
  src/component/connect/i18n/es.yml
  src/component/connect/i18n/fr.yml
  src/component/connect/standalone/example/index.ejs
  src/component/connect/standalone/index.ejs
  src/component/connect/template/ejs/connect.ejs
  src/core/.package.yml
  src/core/example/index.ejs
  src/core/i18n/fr.yml
  tool/build/build.js
  tool/build/example.js
  tool/build/standalone.js
  tool/classes/example/example-node.js
  tool/classes/example/example.js
  tool/classes/i18n/aggregated-i18n.js
  tool/classes/i18n/i18n-locale.js
  tool/classes/i18n/i18n.js
  tool/example/decorator.ejs
  tool/example/element.ejs
  tool/example/example.ejs
  tool/example/folder.ejs
  tool/example/layout.ejs
  tool/example/package.ejs
  tool/example/script.ejs
  tool/example/standalone.ejs
  tool/example/style.ejs
  tool/example/subdir.ejs
  tool/example/wrapper.ejs
  tool/generate/config.js
  tool/generate/font-subset.js
  tool/generate/markdown.js
  tool/generate/readme.js
  tool/tool.js
Labels: évolution

#350 fix(core): correction du sens de l'extension du soulignement
  src/core/style/action/tool/_link.scss
Labels: correctif

#362 fix(core): correction du sens de l'extension du soulignement
  src/core/style/action/tool/_link.scss
Labels: correctif

#354 fix(pagination): correction couleur des liens de pagination en 'button' [DS-2577]
  src/core/style/action/tool/_button.scss
Labels: correctif

#352 fix(content, core): bug ratio vidéos ios [DS-2188]
  src/component/content/deprecated/example/sample/media-vid-default.ejs
  src/core/example/media/sample/svg--illu.ejs
  src/core/style/media/_module.scss
  src/core/style/media/_setting.scss
  src/core/style/media/module/_fluid.scss
  src/core/style/media/module/_ratio.scss
  src/core/style/media/module/_responsive.scss
  src/core/variables.scss
Labels: correctif
