Repository GouvernementFR/dsfr, pull requests merged in 2022-12, with the labels that each got.

#484 fix(tile): retrait du hover sur l'image [DS-2725]
  src/component/tile/deprecated/style/_module.scss
  src/component/tile/style/module/_default.scss
Labels: correctif

#479 fix(header): Alignement à gauche des raccourcis sans icones [DS-2951]
  src/component/header/style/module/_links.scss
Labels: correctif

#490 fix(core): correctif de la taille minimum de l'underline des liens [DS-2987]
  src/core/style/action/tool/_link.scss
Labels: correctif

#492 fix(address): Inversion ordre immeuble et batiment [DS-2976]
  src/pattern/address/example/data/complement.json.ejs
Labels: correctif

#494 fix(artwork): depreciation des xlink dans les artwork [DS-2979]
  src/core/script/artwork/artwork.js
  src/core/template/ejs/artwork/pictogram.ejs
Labels: évolution

#496 feat(core): Ajout des valeurs des breakpoints en custom var css [DS-2953]
  src/core/style/spacing/_module.scss
  src/core/style/spacing/module/_breakpoint.scss
Labels: ajout

#497 fix(header): Copie du selecteur de langue sans acces rapide [DS-2950]
  src/component/header/main.js
Labels: correctif

#499 fix(core): correction icone lien externe IE
  src/component/radio/legacy.scss
  src/component/radio/main.scss
  src/component/tab/script/tab/tabs-list.js
  src/core/style/action/legacy/_link.scss
Labels: correctif

#500 fix(pagination): ajustement taille et écart des boutons [DS-2931]
  src/component/pagination/example/sample/pagination.ejs
  src/component/pagination/style/_module.scss
  src/component/pagination/style/_setting.scss
Labels: évolution
