Repository GouvernementFR/dsfr, pull requests merged in 2022-03, with the labels that each got.

#225 fix(core, tab, modal, button): injection js de styles en variables css [DS-2409][DS-2373]
  src/component/button/style/module/_buttons-group.scss
  src/component/modal/script/modal/modal-body.js
  src/component/modal/style/_module.scss
  src/component/tab/script/tab/tab-panel-direction.js
  src/component/tab/script/tab/tab-panel.js
  src/component/tab/script/tab/tab-selector.js
  src/component/tab/script/tab/tabs-group.js
  src/component/tab/style/_module.scss
  src/component/toggle/style/module/_toggle.scss
  src/core/script/api/internals.js
  src/core/script/api/scroll/scroll-locker.js
  src/core/script/api/utilities/motion/index.js
  src/core/script/api/utilities/motion/transition-selector.js
  src/core/script/collapse/collapse.js
  src/core/script/equisized/equisized.js
  src/core/script/equisized/equisizeds-group.js
  src/core/style/_module.scss
  src/core/style/collapse/_tool.scss
  src/core/style/display/module/_no-scroll.scss
  src/core/style/motion/_module.scss
Labels: correctif

#224 feat(connect): ajout description et lien france connect [DS-2402]
  src/component/connect/.package.yml
  src/component/connect/example/index.ejs
  src/component/connect/example/sample/connect-default.ejs
  src/component/connect/example/sample/connect-plus.ejs
  src/component/connect/standalone/index.ejs
  src/component/connect/style/_module.scss
  src/component/connect/template/ejs/connect.ejs
Labels: évolution

#231 feat(core): ajout d'icones [DS-2405]
  src/core/example/icon/index.ejs
  src/core/icon/deprecated/svg/arrow-go-back-fill.svg
  src/core/icon/deprecated/svg/arrow-go-back-line.svg
  src/core/icon/deprecated/svg/font-size.svg
  src/core/icon/deprecated/svg/home-4-fill.svg
  src/core/icon/deprecated/svg/home-4-line.svg
  src/core/icon/deprecated/svg/image-fill.svg
  src/core/icon/deprecated/svg/image-line.svg
  src/core/icon/deprecated/svg/italic.svg
  src/core/icon/deprecated/svg/line-chart-fill.svg
  src/core/icon/deprecated/svg/line-chart-line.svg
  src/core/icon/deprecated/svg/link-unlink.svg
  src/core/icon/deprecated/svg/list-ordered.svg
  src/core/icon/deprecated/svg/list-unordered.svg
  src/core/icon/deprecated/svg/map-pin-2-fill.svg
  src/core/icon/deprecated/svg/map-pin-2-line.svg
  src/core/icon/deprecated/svg/phone-fill.svg
  src/core/icon/deprecated/svg/phone-line.svg
  src/core/icon/deprecated/svg/road-map-fill.svg
  src/core/icon/deprecated/svg/road-map-line.svg
  src/core/icon/deprecated/svg/rss-fill.svg
  src/core/icon/deprecated/svg/rss-line.svg
  src/core/icon/deprecated/svg/timer-fill.svg
  src/core/icon/deprecated/svg/timer-line.svg
  src/core/icon/deprecated/svg/zoom-in-fill.svg
  src/core/icon/deprecated/svg/zoom-in-line.svg
  src/core/icon/deprecated/svg/zoom-out-fill.svg
  src/core/icon/deprecated/svg/zoom-out-line.svg
  src/core/icon/svg/bold.svg
  src/core/icon/svg/highlight.svg
Labels: ajout

#229 fix: margin bottom des textes et titres en css prop [DS-2013]
  src/component/callout/style/_module.scss
  src/component/consent/style/module/_services.scss
  src/component/footer/style/module/_bottom.scss
  src/component/footer/style/module/_content.scss
  src/component/footer/style/module/_top.scss
  src/component/highlight/style/_module.scss
  src/component/logo/style/_module.scss
  src/component/modal/style/_module.scss
  src/component/quote/style/_module.scss
  src/component/summary/style/_module.scss
Labels: correctif

#232 fix(tab): correction z-index des tab-panels [DS-2420]
  src/component/tab/style/_module.scss
Labels: correctif

#230 fix(modal): <dialog> masqué en no-css [DS-2423]
  src/component/modal/script/modal/modal.js
Labels: correctif

#223 fix(sidemenu): correction hauteur sidemenu sticky [DS-2355]
  src/component/sidemenu/style/module/_variants.scss
Labels: correctif

#215 feat(footer): ajout d'un sample de footer paramétrable [DS-2132][DS-2408]
  src/component/footer/example/index.ejs
  src/component/footer/example/sample/footer-minimal.ejs
  src/component/footer/example/sample/footer-operator.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/example/sample/footer-total.ejs
  src/component/footer/example/sample/footer.ejs
  src/component/footer/style/_module.scss
  src/component/footer/style/module/_partners.scss
  src/component/footer/template/ejs/content.ejs
  src/component/header/example/sample/header.ejs
  src/component/skiplink/example/prepend.ejs
Labels: ajout

#227 fix(collapse): corrige le collapse multi-navigateurs [DS-2332]
  src/core/script/collapse/collapse.js
Labels: correctif

#226 fix(megamenu): corrige erreur js en mode no-module [DS-2379]
  src/core/script/api/modules/font-swap/font-swap.js
  src/core/script/disclosure/disclosures-group.js
Labels: correctif

#233 feat(link): Ajout du lien "back to top" [DS-286]
  src/component/link/example/index.ejs
  src/component/link/example/sample/link-back-to-top.ejs
  src/component/skiplink/style/_module.scss
  src/component/skiplink/template/ejs/skiplinks.ejs
  src/core/example/icon/index.ejs
  src/core/icon/deprecated/svg/arrow-up-fill.svg
  tool/example/example.ejs
Labels: ajout

#238 fix(connect): retrait du hint text [DS-2402]
  src/component/connect/style/_scheme.scss
  src/component/connect/style/module/_group.scss
  src/component/connect/template/ejs/connect.ejs
Labels: correctif

#239 fix(connect): correction taille du lien en sm [DS-2402]
  src/component/connect/style/_scheme.scss
  src/component/connect/style/module/_group.scss
  src/component/connect/template/ejs/connect.ejs
Labels: correctif

#261 fix(connect): retrait description & ajout target blank [DS-2490]
  src/component/connect/example/sample/connect-default.ejs
  src/component/connect/example/sample/connect-plus.ejs
Labels: correctif

#258 fix(tag): correction tag activable sm et dans un group sm [DS-2491]
  src/component/tag/style/_scheme.scss
  src/component/tag/style/_tool.scss
Labels: correctif
