Repository GouvernementFR/dsfr, pull requests merged in 2023-04, with the labels that each got.

#571 ✨ feat(artwork): ajout picto document-add [DS-3210]
  src/core/asset/artwork/pictograms/document/document-add.svg
Labels: ajout, Prêt

#559 :sparkles: feat(readme): Mise à jour du readme [DS-3193]
  README.md
Labels: correctif, documentation

#566 :bug: fix(modal): correctif prise de focus au focus-trap [DS-3211]
  src/component/modal/script/modal/focus-trap.js
Labels: correctif

#574 :bug: fix(password): correctif erreur getModifierState [DS-2940]
  src/component/password/script/password/password-input.js
Labels: correctif

#573 :bug: fix(consent): consent placeholder video mal centré [DS-3026]
  src/core/style/media/module/_responsive.scss
Labels: correctif, Prêt

#568 :sparkles: feat(footer): évolution des mentions légales [DS-3140]
  src/component/footer/example/sample/footer.ejs
Labels: évolution, Prêt

#563 :bug: fix(notice): ajoute 'importante' au bandeau d'information importante [DS-3073]
  src/component/notice/.package.yml
  src/component/notice/example/index.ejs
Labels: correctif

#565 🐛 fix(transcription): corrige largeur du bouton a l'ouverture de la modale [DS-3070]
  src/component/transcription/style/_module.scss
Labels: correctif, Prêt

#580 🐛 fix(build): changement des path pour compiler sur windows [DS-2992]
  CONTRIBUTING.md
  tool/build/scripts.js
  tool/build/styles.js
  tool/utilities/file.js
Labels: correctif

#581 feat(analytics): environnement spa
  src/analytics/example/spa/angular/index.ejs
  src/analytics/example/spa/react/index.ejs
  src/analytics/example/spa/route.js
  src/analytics/example/spa/vue/index.ejs
  src/analytics/i18n/fr.yml
Labels: correctif

#561 ✨ feat(changelog): ajoute changelog auto-généré [DS-3070]
  .auto-changelog
  CHANGELOG.md
  CONTRIBUTING.md
  changelog-template.hbs
  package.json
  yarn.lock
Labels: évolution, Prêt

#588 :sparkles: feat(analytics): polyfill legacy [DS-3221]
  src/analytics/script/analytics/action/action.js
  src/analytics/script/analytics/utils/hierarchy/member.js
  src/analytics/script/integration/core/actionee.js
  src/legacy/script/index.js
  src/legacy/script/polyfill-io/array-from-polyfill.min.js
  src/legacy/script/polyfill-io/array-prototype-flat-polyfill.min.js
  src/legacy/script/polyfill-io/element-prototype-closest-polyfill.min.js
  src/legacy/script/polyfill-io/object-assign-polyfill.min.js
  src/legacy/script/polyfill-io/object-entries-polyfill.min.js
  src/legacy/script/polyfill-io/object-from-entries-polyfill.min.js
  src/legacy/script/polyfill-io/object-get-own-property-symbols-polyfill.min.js
  src/legacy/script/polyfill-io/object-values-polyfill.min.js
  src/legacy/script/polyfill-io/promise-polyfill.min.js
  src/legacy/script/polyfill-io/url-search-params-polyfill.min.js
Labels: correctif
