Repository GouvernementFR/dsfr, pull requests merged in 2023-07, with the labels that each got.

#642 🐛 fix(changelog): correctif inclusion des html [DS-3317]
  tool/classes/changelog/changelog.ejs
Labels: correctif, Prêt, maj 1.9.3

#647 :bug: fix(analytics): correctif hiérarchie [DS-3394]
  src/analytics/script/analytics/utils/hierarchy/member.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#643 📝 docs(analytics): correction doc analytics & readme [DS-3396]
  README.md
  src/analytics/doc/analytics.md
  src/analytics/doc/analytics/collector/page.md
  src/analytics/doc/analytics/collector/site.md
Labels: correctif, Prêt, maj 1.10.0-rc.1

#646 🐛 fix(core): correctif bug proxy Toggle [DS-3351]
  src/core/script/action/toggle/toggle.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#644 ⬆️ chore(*): montée de version NodeJS 18 [DS-3319]
  package.json
Labels: dependencies, Prêt, maj 1.10.0-rc.1

#650 🐛 fix(core): correctif padding négatif [DS-3322]
  src/core/style/spacing/tool/_margin.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#649 🐛 fix(pattern): dénomination des blocs fonctionnels [DS-3393]
  src/component/input/input-email/.package.yml
  src/component/input/input-email/i18n/fr.yml
  src/component/input/input-tel/.package.yml
  src/component/input/input-tel/i18n/fr.yml
  src/pattern/.folder.yml
  src/pattern/address/.package.yml
  src/pattern/address/i18n/fr.yml
  src/pattern/civility/.package.yml
  src/pattern/company/.package.yml
  src/pattern/company/i18n/fr.yml
  src/pattern/date/.package.yml
  src/pattern/date/i18n/fr.yml
  src/pattern/name/.package.yml
  src/pattern/name/i18n/fr.yml
  src/pattern/nationality/.package.yml
  src/pattern/nationality/i18n/fr.yml
Labels: correctif, Prêt, maj 1.10.0-rc.1

#652 🐛 fix(account): accessibilité champs obligatoires [DS-3320]
  src/page/account/login/example/data/login.json.ejs
  src/page/account/login/i18n/fr.yml
  src/page/account/register/example/data/address.json.ejs
  src/page/account/register/example/data/identity.json.ejs
  src/page/account/register/example/data/login.json.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#654 🐛 fix(*): accessibilité aria-live [DS-3323]
  src/analytics/example/spa/agnostic/index.ejs
  src/analytics/example/spa/angular/_index.ejs
  src/analytics/example/spa/react/index.ejs
  src/analytics/example/spa/vue/index.ejs
  src/component/form/template/ejs/message/messages-group.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#655 🐛 fix(unexpected): corrige groupe de bouton vide [DS-3324]
  src/page/response/template/ejs/response.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#656 🐛 feat(company): accessibilité lien externe [DS-3326]
  src/component/tile/template/ejs/content.ejs
  src/pattern/company/example/data/siret.json.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#648 🐛 fix(password): bug icône [DS-3379]
  src/component/input/input-base/template/ejs/input.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#658 🐛 fix(link): corrige graisse lien de téléchargement [DS-3373]
  src/component/link/style/module/_download.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#659 🐛 fix(company): retrait des pluriels [DS-3392]
  src/pattern/company/i18n/fr.yml
  src/pattern/name/example/data/name.json.ejs
  src/pattern/name/i18n/fr.yml
Labels: correctif, Prêt, maj 1.10.0-rc.1

#661 :bug: fix(pagination): correctif régression href des exemples [DS-3380]
  src/component/pagination/example/sample/pagination.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#657 :bug: fix(card, tile): ajout version sans liens, target blank, et mise à jour des exemples [DS-3359, DS-3330, DS-3387, DS-3362, DS-3358]
  src/component/card/example/download/index.ejs
  src/component/card/example/download/sample/card-download.ejs
  src/component/card/example/download/sample/sample-assess-file.ejs
  src/component/card/example/download/sample/sample-content.ejs
  src/component/card/example/download/sample/sample-img.ejs
  src/component/card/example/download/sample/sample-lang.ejs
  src/component/card/example/download/sample/sample-no-img.ejs
  src/component/card/example/download/sample/sample-sizes.ejs
  src/component/card/example/index.ejs
  src/component/card/example/sample/card-default.ejs
  src/component/card/example/sample/sample-enlarge.ejs
  src/component/card/example/sample/sample-no-link.ejs
  src/component/card/example/sample/sample-sizes.ejs
  src/component/card/style/_legacy.scss
  src/component/card/style/_scheme.scss
  src/component/card/style/module/_content.scss
  src/component/card/style/module/_default.scss
  src/component/card/style/module/_download.scss
  src/component/card/style/module/_lg.scss
  src/component/card/style/module/_sm.scss
  src/component/tile/example/download/index.ejs
  src/component/tile/example/download/sample/sample-assess-file.ejs
  src/component/tile/example/download/sample/sample-content.ejs
  src/component/tile/example/download/sample/sample-lang.ejs
  src/component/tile/example/download/sample/sample-no-img.ejs
  src/component/tile/example/download/sample/sample-sizes.ejs
  src/component/tile/example/download/sample/sample-vertical.ejs
  src/component/tile/example/index.ejs
  src/component/tile/example/layout-english.ejs
  src/component/tile/example/sample/sample-content.ejs
  src/component/tile/example/sample/sample-disabled.ejs
  src/component/tile/example/sample/sample-enlarge.ejs
  src/component/tile/example/sample/sample-grid.ejs
  src/component/tile/example/sample/sample-horizontal.ejs
  src/component/tile/example/sample/sample-icon.ejs
  src/component/tile/example/sample/sample-no-img.ejs
  src/component/tile/example/sample/sample-no-link.ejs
  src/component/tile/example/sample/sample-sizes.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/index.scss
  src/component/tile/style/_scheme.scss
  src/component/tile/style/_tool.scss
  src/component/tile/style/module/_default.scss
  src/component/tile/style/module/_sm.scss
  src/component/tile/template/ejs/content.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#662 🐛 fix(consent): correctif espacement et couleur [DS-3370, DS-3369]
  src/component/consent/style/_scheme.scss
  src/component/consent/style/_setting.scss
  src/component/consent/style/module/_services.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#663 🐛 fix(modal): suppression exemple des liens dans la zone d'action [DS-3377]
  src/analytics/example/component/modal/modal-links/index.ejs
  src/analytics/i18n/fr.yml
  src/component/modal/example/index.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#666 🐛 fix(tooltip): mise a jour exemple [DS-3371]
  src/component/tooltip/example/sample/tooltip-table.ejs
  src/component/tooltip/i18n/fr.yml
Labels: correctif, Prêt, maj 1.10.0-rc.1

#668 :bug: fix(footer): retrait de CSS obsolète [DS-3404]
  src/component/footer/style/module/_bottom.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#664 🐛 fix(name): a11y - gestion du focus [DS-3325]
  src/pattern/name/example/index.ejs
  src/pattern/name/example/js/add-firstname.js
  src/pattern/name/example/js/remove-firstname.js
  src/pattern/name/example/js/toggle-disabled.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#669 :bug: fix(password): retrait du bouton natif sur edge [DS-3378]
  src/component/password/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#671 🐛 fix(date): ajustement exemples [DS-3390]
  src/pattern/date/example/data/date.json.ejs
  src/pattern/date/example/sample/date-global-error.ejs
  src/pattern/date/example/sample/date-single-error.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#680 :bug: fix(transcription): déplacement bouton modale [DS-3388]
  src/component/transcription/example/sample/footer/actions.ejs
  src/component/transcription/example/sample/transcription-default.ejs
  src/component/transcription/template/ejs/transcription.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#681 :bug: fix(analytics): correctif page.date [DS-3321]
  src/analytics/doc/analytics/collector/page.md
  src/analytics/example/config.ejs
  src/analytics/script/analytics/utils/type-validator.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#675 🐛 fix(follow): ajoute d'exemple [DS-3383]
  src/component/follow/.package.yml
  src/component/follow/example/data/newsletter-alert.json.ejs
  src/component/follow/example/index.ejs
  src/component/follow/example/sample/socials-newsletter-alert.ejs
  src/component/follow/template/ejs/newsletter.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#676 🐛 fix(civility): correctif taille des boutons radio [DS-3389]
  src/pattern/civility/example/data/honorific-radio.json.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#679 🐛 fix(input): ajustement champs particuliers [DS-3403]
  src/component/form/style/module/_fieldset.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#678 ✨ feat(navigation, header, sidemenu): homogénéisation des espacements et indentation [DS-3356]
  src/component/accordion/style/_module.scss
  src/component/header/style/module/_nav.scss
  src/component/navigation/style/module/_default.scss
  src/component/navigation/style/module/_mega-menu.scss
  src/component/navigation/style/module/_menu.scss
  src/component/navigation/style/scheme/_default.scss
  src/component/sidemenu/style/module/_action.scss
  src/component/sidemenu/style/module/_inner.scss
  src/component/sidemenu/style/module/_list.scss
Labels: évolution, Prêt, maj 1.10.0-rc.1

#682 :bug: fix(card, tile): correctif token title [DS-3430]
  src/component/card/style/_scheme.scss
  src/component/tile/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#683 :bug: fix(card, tile): correctif lien externe et désactivé [DS-3458]
  i18n/fr.yml
  src/component/card/example/index.ejs
  src/component/card/example/sample/card-default.ejs
  src/component/card/template/ejs/content.ejs
  src/component/tile/example/download/sample/sample-assess-file.ejs
  src/component/tile/example/download/sample/sample-content.ejs
  src/component/tile/example/download/sample/sample-lang.ejs
  src/component/tile/example/download/sample/sample-no-img.ejs
  src/component/tile/example/download/sample/sample-sizes.ejs
  src/component/tile/example/download/sample/sample-vertical.ejs
  src/component/tile/example/index.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/template/ejs/content.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#687 :bug: fix(card,tile): corrige erreur de syntaxe ejs + lint
  src/component/card/example/sample/card-default.ejs
  src/component/card/style/module/_default.scss
  src/component/password/style/_module.scss
  src/component/tile/example/sample/tile-default.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.1

#685 ✨ feat(tile): ajouts de variations de tuiles [DS-3464]
  src/component/tile/example/index.ejs
  src/component/tile/example/layout-english.ejs
  src/component/tile/example/sample/sample-variations.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/style/_scheme.scss
  src/component/tile/template/ejs/tile.ejs
Labels: évolution, Prêt, maj 1.10.0-rc.1

#686 🐛 fix(tooltip) : a11y tooltip hover [DS-3461,DS-3462,DS-3463]
  src/component/tooltip/example/sample/tooltip-text.ejs
  src/component/tooltip/script/tooltip/tooltip-referent.js
  src/component/tooltip/script/tooltip/tooltip.js
  src/component/tooltip/style/_module.scss
  src/component/tooltip/template/ejs/tooltip.ejs
  src/core/script/placement/placement-referent.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#691 :bug: fix(tooltip,modal): interaction globale et focus iOS [DS-3460,DS-3395]
  src/analytics/doc/analytics/installation/configuration.md
  src/component/modal/script/modal/modal.js
  src/component/tooltip/script/tooltip/tooltip-referent.js
  src/core/index.js
  src/core/script/api/modules/register/instance.js
  src/core/script/api/modules/register/key-codes.js
  src/core/script/api/modules/stage/root-emission.js
  src/core/script/api/modules/stage/root-selector.js
  src/core/script/api/modules/stage/root.js
Labels: correctif, Prêt, maj 1.10.0-rc.1

#693 :sparkles: feat(colors): ajout des utilitaires de couleur flat [DS-3484]
  module/color/variable/_decisions.scss
Labels: évolution, Prêt, maj 1.10.0-rc.2

#696 :bug: fix(core): correctif sur KeyAction [DS-3488]
  src/core/script/api/modules/register/instance.js
Labels: correctif, Prêt, maj 1.10.0-rc.2

#698 :bug: fix(sidemenu): correction de la couleur des liens du sidemenu [DS-3493]
  src/component/sidemenu/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#694 🐛 fix(password): correctif accessibilité des messages [DS-3327]
  src/analytics/example/spa/agnostic/route.js.ejs
  src/component/form/style/module/_message.scss
  src/component/form/template/ejs/fieldset/fieldset.ejs
  src/component/form/template/ejs/message/builder.js.ejs
  src/component/input/input-base/template/ejs/input.ejs
  src/component/password/example/sample/password-register.ejs
  src/component/password/i18n/fr.yml
  src/component/password/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#697 :bug: fix(header): correctif régression scroll horizontal [DS-3514]
  src/component/header/style/module/_nav.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#699 🐛 fix(modal): préviens décalage mobile [DS-3495]
  src/component/modal/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#700 🐛 fix(*): mise à jour des liens du readme
  README.md
Labels: correctif, Prêt

#702 🐛 fix(link): correctif téléchargement multiligne [DS-3509]
  src/component/link/style/module/_download.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#703 🐛 fix(toggle): retrait tap-highlight-color iOS [DS-3502]
  src/component/toggle/style/module/_default.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#705 🐛 fix(card, tile): correctif IE 11 [DS-3515]
  src/component/card/style/_legacy.scss
  src/component/tile/style/_legacy.scss
  src/component/tile/style/module/_default.scss
  src/component/tile/style/module/_download.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#707 ✨ feat(*): Ajout d'un meta tag iOS [DS-3507]
  README.md
  tool/example/example.ejs
Labels: ajout, Prêt, maj 1.10.0-rc.2

#708 🐛 fix(transcription, content): correctif title et label bouton Agrandir [DS-3512, DS-3501]
  src/component/content/example/sample/media-default.ejs
  src/component/transcription/template/ejs/transcription.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.2

#704 🐛 fix(tile): correctif espacements version dépreciée [DS-3508]
  src/component/tile/deprecated/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0-rc.1

#713 :bug: fix(core): stabilisation disclosure [DS-3519]
  src/core/script/disclosure/disclosures-group.js
Labels: correctif, Prêt, maj 1.10.0-rc.2

#711 ✨ feat(core, password): boutons spéciaux input Safari [DS-3510]
  src/component/password/style/_module.scss
  src/component/password/style/_scheme.scss
  src/core/style/action/module/_input.scss
Labels: correctif, ajout, Prêt, maj 1.10.0-rc.2

#714 🐛 fix(follow): orthographe message de confirmation [DS-3492]
  src/component/follow/example/data/newsletter-alert.json.ejs
Labels: correctif, Prêt, maj 1.10.0-rc.2

#715 fix(form): correctif focus des radios riches dépréciés [DS-3489]
  src/component/form/deprecated/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2

#716 :bug: fix(modal): retour de focus fermeture clavier [DS-3513]
  src/component/modal/script/modal/modal.js
Labels: correctif, Prêt, maj 1.10.0-rc.2

#712 🐛 fix(form): correctif barre état iOS [DS-3505]
  src/component/form/deprecated/style/_module.scss
  src/component/form/style/module/_fieldset.scss
Labels: correctif, Prêt, maj 1.10.0-rc.2
