Repository GouvernementFR/dsfr, pull requests merged in 2023-05, with the labels that each got.

#601 feat(analytics): Page d'exemple SPA agnostic [DS-3224]
  src/analytics/example/config.ejs
  src/analytics/example/spa/agnostic/_index.ejs
  src/analytics/example/spa/agnostic/change.js.ejs
  src/analytics/example/spa/agnostic/config.ejs
  src/analytics/example/spa/agnostic/index.ejs
  src/analytics/example/spa/agnostic/route.js
  src/analytics/example/spa/agnostic/route.js.ejs
  src/analytics/example/spa/react/config.ejs
  src/analytics/example/spa/vue/config.ejs
  src/analytics/example/spa/vue/index.ejs
  tool/build/example.js
  tool/classes/example/example-node.js
  tool/example/config.ejs
  tool/example/example.ejs
Labels: ajout

#590 :sparkles: feat(*): nouvelle version interne changelog [DS-3230]
  .auto-changelog
  CHANGELOG.md
  changelog-template.hbs
  package.json
  tool/classes/changelog/changelog.ejs
  tool/classes/changelog/changelog.js
  tool/classes/changelog/commit.js
  tool/classes/changelog/remote.js
  tool/classes/changelog/tag.js
  tool/classes/changelog/utils.js
  tool/tool.js
  yarn.lock
Labels: ajout, Prêt

#503 :bug: fix(password, account): correction capslock safari [DS-2942]
  src/component/input/input-base/style/_module.scss
  src/component/input/input-base/style/_scheme.scss
  src/component/input/input-base/style/_tool.scss
  src/component/password/script/password/password-toggle.js
  src/component/password/style/_module.scss
  src/component/password/template/ejs/password.ejs
  src/page/account/login/example/data/login.json.ejs
  src/page/account/register/example/data/login.json.ejs
Labels: correctif, Prêt

#572 :bug: fix(modal): correction ombre modal footer [DS-3061]
  src/component/modal/example/index.ejs
  src/component/modal/example/sample/body/text.ejs
  src/component/modal/legacy.scss
  src/component/modal/script/modal/modal-body.js
  src/component/modal/script/modal/modal-selector.js
  src/component/modal/style/_legacy.scss
  src/component/modal/style/_module.scss
  src/component/modal/style/_scheme.scss
Labels: correctif, Prêt

#597 🐛 fix(button, theme): retrait propriété css :where [DS-2759]
  module/selector/mixin/_theme.scss
  src/component/button/style/module/_group.scss
Labels: correctif, Prêt

#594 🐛 fix(core): La valeur no-wrap n’existe pas dans la spécification CSS
  src/core/style/display/module/_hr.scss
Labels: correctif, Prêt

#596 :bug: fix(analytics): correctifs divers [DS-3222,DS-3231,DS-3232,DS-3242,DS-3245,DS-3246,DS-3250,DS-3251,DS-3253]
  src/analytics/example/component/checkbox/checkbox-checked/index.ejs
  src/analytics/example/component/checkbox/index.ejs
  src/analytics/example/config.ejs
  src/analytics/example/spa/agnostic/_index.ejs
  src/analytics/example/spa/agnostic/change.js.ejs
  src/analytics/example/spa/agnostic/config.ejs
  src/analytics/example/spa/agnostic/index.ejs
  src/analytics/example/spa/agnostic/route.js
  src/analytics/example/spa/agnostic/route.js.ejs
  src/analytics/example/spa/react/config.ejs
  src/analytics/example/spa/vue/config.ejs
  src/analytics/example/spa/vue/index.ejs
  src/analytics/main.js
  src/analytics/script/analytics/action/action-element.js
  src/analytics/script/analytics/action/action.js
  src/analytics/script/analytics/action/actions.js
  src/analytics/script/analytics/analytics.js
  src/analytics/script/analytics/cmp/consent-manager-platform.js
  src/analytics/script/analytics/engine/collector.js
  src/analytics/script/analytics/engine/queue.js
  src/analytics/script/analytics/facade/debug.js
  src/analytics/script/analytics/facade/init.js
  src/analytics/script/analytics/utils/restricted.js
  src/analytics/script/integration/component/accordion/accordion-actionee.js
  src/analytics/script/integration/component/button/button-actionee.js
  src/analytics/script/integration/component/component-actionee.js
  src/analytics/script/integration/component/components.js
  src/analytics/script/integration/component/pagination/pagination-actionee.js
  src/analytics/script/integration/component/pagination/pagination-link-actionee.js
  src/analytics/script/integration/component/pagination/pagination-selector.js
  src/analytics/script/integration/component/search/search-actionee.js
  src/analytics/script/integration/component/select/select-actionee.js
  src/analytics/script/integration/component/tile/tile-actionee.js
  src/analytics/script/integration/component/upload/upload-actionee.js
  src/analytics/script/integration/core/actionee.js
  src/analytics/standalone/api.js
  src/analytics/standalone/example/index.ejs
  src/analytics/standalone/main.js
  src/component/pagination/template/ejs/pagination.ejs
  src/core/script/api/modules/register/instance.js
  src/core/script/api/modules/stage/element.js
  tool/build/example.js
  tool/classes/example/example-node.js
  tool/example/config.ejs
  tool/example/example.ejs
  yarn.lock
Labels: correctif

#599 :pencil: doc(analytics): doc analytics en markdown [DS-3215]
  doc/Analytics-1.9.2.pdf
  src/analytics/doc/analytics.md
  src/analytics/doc/analytics/actions.md
  src/analytics/doc/analytics/actions/component-actions.md
  src/analytics/doc/analytics/actions/custom-actions.md
  src/analytics/doc/analytics/collector.md
  src/analytics/doc/analytics/collector/analytics.md
  src/analytics/doc/analytics/collector/funnel.md
  src/analytics/doc/analytics/collector/page.md
  src/analytics/doc/analytics/collector/search.md
  src/analytics/doc/analytics/collector/site.md
  src/analytics/doc/analytics/collector/user.md
  src/analytics/doc/analytics/installation.md
  src/analytics/doc/analytics/installation/cmp.md
  src/analytics/doc/analytics/installation/configuration.md
  src/analytics/doc/analytics/installation/opt.md
  src/analytics/script/analytics/action/action-element.js
  src/analytics/script/integration/component/badge/badge-actionee.js
  src/analytics/script/integration/component/connect/connect-link-actionee.js
Labels: documentation

#600 🐛 fix(breadcrumb): ajoute une page exemple alternative [DS-3254]
  src/analytics/example/component/breadcrumb/breadcrumb-button/index.ejs
  src/analytics/example/component/breadcrumb/index.ejs
  src/component/breadcrumb/example/alternative/index.ejs
  src/component/breadcrumb/example/index.ejs
  src/component/breadcrumb/example/sample/sample-a.ejs
  src/component/breadcrumb/example/sample/sample-button.ejs
  src/component/breadcrumb/i18n/fr.yml
  src/component/breadcrumb/style/_module.scss
  src/component/breadcrumb/template/ejs/breadcrumb.ejs
Labels: correctif
