Repository GouvernementFR/dsfr, pull requests merged in 2023-11, with the labels that each got.

#719 🐛 fix(consent): ajoute un niveau de titre sur la bannière de consentement [DS-2257]
  src/component/consent/template/ejs/placeholder.ejs
Labels: correctif, Prêt, maj 1.10.0

#720 🐛 fix(modal): a11y retire la liste dans la zone d'actions [DS-1257]
  src/component/button/style/tool/_group.scss
  src/component/button/template/ejs/buttons-group.ejs
  src/component/modal/example/sample/footer/buttons.ejs
Labels: correctif, Prêt

#721 🐛 fix(quote): mise à jour des exemples [DS-2902]
  src/component/quote/example/index.ejs
  src/component/quote/style/_module.scss
  src/component/quote/template/ejs/quote.ejs
Labels: correctif, Prêt, maj 1.10.0

#723 🐛 fix(page-unexpected): textes [DS-3398]
  src/page/response/unexpected/i18n/fr.yml
Labels: correctif, Prêt, maj 1.10.0

#724 🐛 fix(stepper): mise à jour de la structure [DS-3372]
  src/component/stepper/style/_module.scss
  src/component/stepper/template/ejs/stepper.ejs
Labels: correctif, Prêt, maj 1.10.0

#727 🐛 fix(header): mise à jour des exemples [DS-3367, DS-3544]
  src/component/button/style/_module.scss
  src/component/button/style/_scheme.scss
  src/component/button/style/module/_account.scss
  src/component/button/style/module/_briefcase.scss
  src/component/button/style/module/_team.scss
  src/component/header/example/index.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/style/_scheme.scss
  src/component/header/style/module/_links.scss
  src/component/header/template/ejs/tools.ejs
  src/component/translate/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0

#734 ✨ feat(select): ajout exemple `<optgroup>` [DS-3374]
  src/component/select/example/index.ejs
  src/component/select/example/sample/option-group.ejs
  src/component/select/template/ejs/select.ejs
Labels: ajout, Prêt, maj 1.10.0

#736 🐛 fix(select): correctifs flèche et intitulé [DS-3534, DS-3536]
  src/component/select/deprecated/example/sample/select.ejs
  src/component/select/example/sample/select.ejs
  src/component/select/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0

#740 🐛 fix(search, input, select): color token & cancel button [DS-3535, DS-3561]
  src/component/input/input-base/style/_scheme.scss
  src/component/search/index.scss
  src/component/search/style/_module.scss
  src/component/search/style/_scheme.scss
  src/component/search/style/_setting.scss
  src/component/select/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#737 ♻️ refactor(link): rel noopener & title target blank [DS-2509]
  src/analytics/example/attribute/index.ejs
  src/analytics/example/component/quote/index.ejs
  src/component/button/template/ejs/button.ejs
  src/component/card/example/sample/card-default.ejs
  src/component/card/template/ejs/content.ejs
  src/component/display/deprecated/example/index.ejs
  src/component/display/example/index.ejs
  src/component/footer/example/sample/footer.ejs
  src/component/footer/template/ejs/content.ejs
  src/component/link/deprecated/template/ejs/link.ejs
  src/component/link/template/ejs/link.ejs
  src/component/navigation/template/ejs/link.ejs
  src/component/notice/example/index.ejs
  src/component/quote/example/sample/quote-default.ejs
  src/component/tag/template/ejs/tag.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/template/ejs/content.ejs
  src/core/example/link/link-raw/index.ejs
  src/core/example/link/link-reset/index.ejs
  src/core/example/reset/index.ejs
  tool/example/decorator.ejs
  tool/example/heading.ejs
Labels: évolution, Prêt, maj 1.10.0

#742 ♻️ refactor(alert): bordures en background-image [DS-3360]
  src/component/alert/style/_module.scss
  src/component/alert/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#745 🐛 fix(header): Token de couleur du texte de service en title grey [DS-3520]
  src/component/header/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#746 ♻️ refactor(highlight, callout): background image à la place de box shadow [DS-3361]
  src/component/callout/style/_module.scss
  src/component/callout/style/_scheme.scss
  src/component/highlight/style/_module.scss
  src/component/highlight/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#747 🐛 fix(breadcrumb, navigation, pagination, sidemenu, translate): selecteur aria-current [DS-3566]
  module/selector/_index.scss
  module/selector/mixin/_current.scss
  src/component/breadcrumb/style/_legacy.scss
  src/component/breadcrumb/style/_module.scss
  src/component/breadcrumb/style/_scheme.scss
  src/component/navigation/style/module/_default.scss
  src/component/navigation/style/scheme/_default.scss
  src/component/pagination/style/_contrast-scheme.scss
  src/component/pagination/style/_contrast.scss
  src/component/pagination/style/_module.scss
  src/component/pagination/style/_scheme.scss
  src/component/sidemenu/style/_scheme.scss
  src/component/sidemenu/style/module/_action.scss
  src/component/translate/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0

#749 🐛 fix(skiplink): visible avec elastic scrolling [DS-3052]
  src/component/skiplink/style/_module.scss
Labels: correctif, Prêt, maj 1.10.0

#750 🐛 fix(password): couleur du texte de la checkbox afficher [DS-3567]
  src/component/password/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#759 🐛 fix(login): corrige espacements [DS-3400]
  src/page/account/login/example/data/login.json.ejs
  src/page/account/login/example/sample/default.ejs
Labels: correctif, Prêt, maj 1.10.0

#771 🐛 fix(toggle): couleur label & espacement activer/desactiver [DS-3526, DS-3527]
  src/component/toggle/style/_scheme.scss
  src/component/toggle/style/module/_default.scss
Labels: correctif, Prêt, maj 1.10.1

#772 🐛 fix(input): combo champ + button en erreur [DS-3583]
  src/component/input/input-base/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.1

#773 🐛 fix(name): bouton ajout et suppression en secondaire [DS-3584]
  src/pattern/name/example/data/name.json.ejs
  src/pattern/name/example/js/add-firstname.js
Labels: correctif, Prêt, maj 1.10.1

#779 🐛 fix(summary): alignement du titre du sommaire [DS-3555]
  src/component/summary/style/_module.scss
Labels: correctif, Prêt, maj 1.10.1

#780 🐛 fix(tag): token de couleur du tag selectionnable [DS-3556]
  src/component/tag/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.1

#782 🐛 fix(skiplink): espacements des liens d'évitement [DS-3533]
  src/component/skiplink/style/_module.scss
Labels: correctif, Prêt, maj 1.10.1

#783 🐛 fix(form): token de couleur de la legend [DS-3550]
  src/component/form/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.1

#786 ♻️ refactor(*): selecteur not combiné [DS-3589]
  src/analytics/script/integration/component/transcription/transcription-selector.js
  src/analytics/script/integration/component/translate/translate-selector.js
  src/component/accordion/script/accordion/accordion-selector.js
  src/component/navigation/script/navigation/navigation-selector.js
  src/component/sidemenu/script/sidemenu/sidemenu-selector.js
Labels: correctif, Prêt, maj 1.10.1

#788 🐛 fix(download): icon-size bug compilation [DS-3593]
  src/component/download/deprecated/style/module/_variants.scss
Labels: correctif, Prêt, maj 1.10.1

#792 🐛 fix(footer): ajustements [DS-3552, DS-3384, DS-3560, DS-3381]
  src/component/footer/example/index.ejs
  src/component/footer/example/sample/footer-partners.ejs
  src/component/footer/example/sample/footer.ejs
  src/component/footer/style/_scheme.scss
  src/component/footer/style/module/_bottom.scss
  src/component/footer/style/module/_content.scss
  src/component/footer/style/module/_default.scss
  src/component/footer/style/module/_partners.scss
  src/component/footer/style/module/_top.scss
  src/component/footer/template/ejs/partners.ejs
Labels: correctif, Prêt, maj 1.10.1

#793 🐛 fix(sidemenu): correction marge interne [DS-3537]
  src/component/sidemenu/style/module/_inner.scss
Labels: correctif, Prêt, maj 1.10.1

#796 🐛 fix(card): alignement du détail & erreur js sur safari <14 [DS-3191]
  src/component/card/style/module/_default.scss
  src/scheme/script/scheme/scheme.js
Labels: correctif, Prêt, maj 1.10.1

#797 🐛 fix(icon): correction de l'icone user-setting-line [DS-3607]
  src/core/icon/user/user-setting-line.svg
Labels: correctif, Prêt

#804 📝 doc(readme): correction du lien de la documentation des icônes
  README.md
Labels: correctif, documentation, Prêt

#813 🐛 fix(connect): adaptabilité de la taille de fonte pour l'accessibilité [DS-3627]
  src/component/connect/i18n/fr.yml
  src/component/connect/standalone/style/_module.scss
  src/component/connect/style/module/_agent.scss
  src/component/connect/style/module/_default.scss
  src/component/connect/style/module/_plus.scss
  src/component/connect/style/scheme/_default.scss
  src/component/connect/style/setting/_size.scss
  src/core/style/action/tool/_button.scss
Labels: correctif, Prêt, maj 1.10.2

#774 📝 doc(readme): mise en forme et précision du README.md
  README.md
Labels: correctif, documentation, Prêt

#760 🐛 fix(radio, radio-rich, toggle, checkbox): met a jour les tokens de couleur [DS-3471]
  src/component/checkbox/style/_scheme.scss
  src/component/radio/style/_tool.scss
  src/component/radio/style/scheme/_default.scss
  src/component/radio/style/scheme/_rich.scss
  src/component/radio/style/scheme/_sm.scss
  src/component/toggle/style/_scheme.scss
Labels: correctif, Prêt, maj 1.10.0

#815 ⬆️ chore(dependencies): met a jour les dépendances Node [DS-3632]
  yarn.lock
Labels: dependencies, à vérifier

#817 ✨ feat(range): ajout du composant curseur [DS-3618]
  module/selector/_index.scss
  module/selector/mixin/_range.scss
  src/component/form/style/_scheme.scss
  src/component/legacy.scss
  src/component/main.js
  src/component/main.scss
  src/component/range/.package.yml
  src/component/range/api.js
  src/component/range/example/index.ejs
  src/component/range/example/sample/range-double.ejs
  src/component/range/example/sample/range-step.ejs
  src/component/range/example/sample/range.ejs
  src/component/range/i18n/fr.yml
  src/component/range/index.js
  src/component/range/index.scss
  src/component/range/legacy.scss
  src/component/range/main.js
  src/component/range/main.scss
  src/component/range/script/range/range-constraints.js
  src/component/range/script/range/range-emission.js
  src/component/range/script/range/range-input.js
  src/component/range/script/range/range-input2.js
  src/component/range/script/range/range-legacy-colors.js
  src/component/range/script/range/range-model.js
  src/component/range/script/range/range-selector.js
  src/component/range/script/range/range-svg.js
  src/component/range/script/range/range.js
  src/component/range/script/range/stroke-line.js
  src/component/range/style/_legacy.scss
  src/component/range/style/_module.scss
  src/component/range/style/_scheme.scss
  src/component/range/template/ejs/range.ejs
  src/core/style/action/module/_cursor.scss
  src/core/style/action/module/_input.scss
  src/core/style/action/setting/_elements.scss
  src/core/style/action/tool/_cursor.scss
  src/core/style/action/tool/_focus.scss
  src/core/style/display/tool/_mask-image.scss
Labels: ajout, Prêt, maj 1.10.1

#816 🐛 fix(core): correctif garbage collection hash [DS-3633]
  src/core/script/api/modules/register/instance.js
Labels: correctif, Prêt, maj 1.10.2

#810 📝 doc(contributing): typos et formattage de la doc de contribution
  CONTRIBUTING.md
Labels: correctif, documentation, Prêt, maj 1.10.2

#819 🐛 fix(toggle): largeur max du label & libellé [DS-3647]
  src/component/toggle/example/sample/toggle-default.ejs
  src/component/toggle/example/sample/toggle-group.ejs
  src/component/toggle/style/module/_default.scss
  src/component/toggle/style/module/_variants.scss
Labels: correctif, Prêt, maj 1.10.2

#821 🐛 fix(build): liens doc sur core & utility [DS-3652]
  tool/example/heading.ejs
Labels: correctif, Prêt, maj 1.11.0

#805 ✨ feat(segmented): ajout du composant contrôle segmenté [DS-3622]
  module/color/function/_colors.scss
  module/color/mixin/_data-uri-svg.scss
  src/component/legacy.scss
  src/component/link/style/tool/_build.scss
  src/component/link/style/tool/_nest.scss
  src/component/main.js
  src/component/main.scss
  src/component/segmented/.package.yml
  src/component/segmented/api.js
  src/component/segmented/example/index.ejs
  src/component/segmented/example/sample/segmented-default.ejs
  src/component/segmented/i18n/fr.yml
  src/component/segmented/index.js
  src/component/segmented/index.scss
  src/component/segmented/legacy.scss
  src/component/segmented/main.js
  src/component/segmented/main.scss
  src/component/segmented/script/segmented/segmented-element.js
  src/component/segmented/script/segmented/segmented-emission.js
  src/component/segmented/script/segmented/segmented-selector.js
  src/component/segmented/script/segmented/segmented.js
  src/component/segmented/style/_legacy.scss
  src/component/segmented/style/_module.scss
  src/component/segmented/style/_scheme.scss
  src/component/segmented/style/_setting.scss
  src/component/segmented/style/_tool.scss
  src/component/segmented/style/module/_default.scss
  src/component/segmented/style/module/_sm.scss
  src/component/segmented/template/ejs/segmented-element.ejs
  src/component/segmented/template/ejs/segmented.ejs
  src/core/style/action/module/_focus.scss
  src/core/style/action/tool/_focus.scss
  src/core/style/display/tool/_sr-only.scss
Labels: ajout, Prêt, maj 1.10.1

#822 🐛 fix(doc): met a jour les liens des pages d'exemple [DS-3641]
  README.md
  src/component/display/.package.yml
  src/component/follow/.package.yml
  src/component/input/input-base/.package.yml
  src/component/input/input-email/.package.yml
  src/component/input/input-tel/.package.yml
  src/component/link/.package.yml
  src/component/password/.package.yml
  src/component/radio/.package.yml
  src/component/skiplink/.package.yml
  src/component/stepper/.package.yml
  src/component/tab/.package.yml
  src/component/tooltip/.package.yml
  src/core/.package.yml
  src/page/account/login/.package.yml
  src/page/account/register/.package.yml
  src/page/response/.folder.yml
  src/pattern/civility/.package.yml
  src/pattern/company/.package.yml
  src/pattern/date/.package.yml
  src/pattern/name/.package.yml
  src/utility/.folder.yml
  src/utility/icons/.folder.yml
  src/utility/icons/icons-buildings/.package.yml
  src/utility/icons/icons-business/.package.yml
  src/utility/icons/icons-communication/.package.yml
  src/utility/icons/icons-design/.package.yml
  src/utility/icons/icons-development/.package.yml
  src/utility/icons/icons-device/.package.yml
  src/utility/icons/icons-document/.package.yml
  src/utility/icons/icons-editor/.package.yml
  src/utility/icons/icons-finance/.package.yml
  src/utility/icons/icons-health/.package.yml
  src/utility/icons/icons-logo/.package.yml
  src/utility/icons/icons-map/.package.yml
  src/utility/icons/icons-media/.package.yml
  src/utility/icons/icons-others/.package.yml
  src/utility/icons/icons-system/.package.yml
  src/utility/icons/icons-user/.package.yml
  src/utility/icons/icons-weather/.package.yml
Labels: correctif, Prêt, maj 1.10.2

#818 🐛 fix(link, card, tile): espacement entre libellé et icone [DS-3643]
  src/component/card/style/module/_content.scss
  src/component/card/template/ejs/content.ejs
  src/component/link/example/index.ejs
  src/component/link/template/ejs/link.ejs
  src/component/tile/style/module/_default.scss
  src/component/tile/template/ejs/content.ejs
Labels: correctif, Prêt, maj 1.10.2

#823 🐛 fix(range): dépendance à scheme [DS-3641]
  src/component/range/.package.yml
  src/component/range/script/range/range.js
Labels: correctif, Prêt, maj 1.11.0

#825 🐛 fix(legacy): bugs IE divers [DS-3641]
  src/component/breadcrumb/style/_module.scss
  src/component/button/style/_legacy.scss
  src/component/card/style/_legacy.scss
  src/component/card/template/ejs/header.ejs
  src/component/checkbox/deprecated/style/_module.scss
  src/component/checkbox/style/_legacy.scss
  src/component/connect/style/module/_plus.scss
  src/component/header/style/_legacy.scss
  src/component/pagination/style/_legacy.scss
  src/component/quote/style/_legacy.scss
  src/component/range/style/_legacy.scss
  src/component/segmented/style/_legacy.scss
  src/component/tag/style/_legacy.scss
  src/component/tag/style/_scheme.scss
  src/core/style/action/legacy/_link.scss
  src/core/style/typography/_legacy.scss
Labels: correctif, Prêt, maj 1.11.0

#833 🐛 fix(*): corrections diverses [DS-3641]
  src/analytics/standalone/example/index.ejs
  src/component/badge/example/index.ejs
  src/component/breadcrumb/style/_module.scss
  src/component/card/example/download/sample/sample-lang.ejs
  src/component/card/style/module/_content.scss
  src/component/card/style/module/_lg.scss
  src/component/card/style/module/_sm.scss
  src/component/checkbox/style/_module.scss
  src/component/checkbox/style/_scheme.scss
  src/component/input/input-base/style/_module.scss
  src/component/main.js
  src/component/quote/style/_module.scss
  src/component/range/style/_module.scss
  src/component/select/style/_module.scss
  src/component/sidemenu/style/_scheme.scss
  src/component/stepper/style/_module.scss
  src/component/tag/style/_scheme.scss
  src/component/translate/style/_scheme.scss
  tool/example/example.ejs
  tool/example/heading.ejs
Labels: correctif, Prêt, maj 1.11.0

#831 🐛 fix(examples): met a jour les pages d'exemple
  src/component/display/deprecated/example/index.ejs
  src/component/display/example/index.ejs
  src/component/download/example/index.ejs
  src/component/highlight/example/index.ejs
  src/component/pagination/example/index.ejs
  src/component/tab/example/index.ejs
  src/component/tile/example/index.ejs
Labels: correctif, documentation, Prêt, maj 1.10.2

#830 🐛 fix(header): augmente le z-index du header [DS-3661]
  module/elevation/variable/_z-indexes.scss
  src/component/header/style/_scheme.scss
Labels: correctif, Prêt, maj 1.11.0

#828 🐛 fix(core): classname IE [DS-3641]
  src/core/script/api/utilities/dom/classes.js
Labels: correctif, Prêt, maj 1.11.0
