Repository GouvernementFR/dsfr, pull requests merged in 2023-03, with the labels that each got.

#542 fix(header): alignement à gauche des raccourcis sans icones [DS-2951]
  src/component/header/style/module/_links.scss
Labels: correctif

#543 fix(core): correctif de la taille minimum de l'underline des liens [DS-2987]
  src/core/style/action/tool/_link.scss
Labels: correctif

#544 fix(address): Inversion ordre immeuble et batiment [DS-2976]
  src/pattern/address/example/data/complement.json.ejs
Labels: correctif

#547 fix(header): copie du sélecteur de langue sans acces rapide [DS-2950]
  src/component/header/main.js
Labels: correctif

#550 fix(scheme): correctif du scheme boot pour omission par ie11
  src/scheme/example/sample/scheme-boot.ejs
  tool/example/example.ejs
Labels: correctif

#555 fix(*): correctifs mineurs pa11y et buble + lint
  src/analytics/example/component/breadcrumb/index.ejs
  src/analytics/example/component/summary/index.ejs
  src/analytics/script/analytics/action/action.js
  src/component/summary/example/sample/summary.ejs
  src/page/response/not-found/example/complete/index.ejs
  src/page/response/not-found/example/contact/index.ejs
  src/page/response/not-found/example/default/index.ejs
  src/page/response/not-found/example/search/index.ejs
  src/page/response/unexpected/example/contact/index.ejs
  src/page/response/unexpected/example/default/index.ejs
  tool/example/example.ejs
  tool/test/pa11y.js
Labels: correctif

#538 fix(tile): svg height 100%
  src/component/tile/deprecated/style/_module.scss
  src/component/tile/style/module/_default.scss
Labels: correctif

#557 feat(analytics): ajoute de nouveaux composants
  src/analytics/example/component/alert/index.ejs
  src/analytics/example/component/badge/index.ejs
  src/analytics/example/component/download/index.ejs
  src/analytics/example/component/input/index.ejs
  src/analytics/example/component/notice/index.ejs
  src/analytics/example/component/pagination/index.ejs
  src/analytics/example/component/quote/index.ejs
  src/analytics/example/component/select/index.ejs
  src/analytics/example/component/table/index.ejs
  src/analytics/example/component/tile/index.ejs
  src/analytics/example/component/toggle/index.ejs
  src/analytics/example/component/transcription/index.ejs
  src/analytics/i18n/fr.yml
  src/analytics/script/integration/component/alert/alert-actionee.js
  src/analytics/script/integration/component/alert/alert-selector.js
  src/analytics/script/integration/component/alert/id.js
  src/analytics/script/integration/component/badge/badge-actionee.js
  src/analytics/script/integration/component/badge/badge-selector.js
  src/analytics/script/integration/component/badge/id.js
  src/analytics/script/integration/component/component-actionee.js
  src/analytics/script/integration/component/components.js
  src/analytics/script/integration/component/download/download-actionee.js
  src/analytics/script/integration/component/download/download-selector.js
  src/analytics/script/integration/component/download/id.js
  src/analytics/script/integration/component/input/id.js
  src/analytics/script/integration/component/input/input-actionee.js
  src/analytics/script/integration/component/input/input-selector.js
  src/analytics/script/integration/component/notice/id.js
  src/analytics/script/integration/component/notice/notice-actionee.js
  src/analytics/script/integration/component/notice/notice-selector.js
  src/analytics/script/integration/component/pagination/id.js
  src/analytics/script/integration/component/pagination/pagination-actionee.js
  src/analytics/script/integration/component/pagination/pagination-selector.js
  src/analytics/script/integration/component/quote/id.js
  src/analytics/script/integration/component/quote/quote-actionee.js
  src/analytics/script/integration/component/quote/quote-selector.js
  src/analytics/script/integration/component/select/id.js
  src/analytics/script/integration/component/select/select-actionee.js
  src/analytics/script/integration/component/select/select-selector.js
  src/analytics/script/integration/component/table/id.js
  src/analytics/script/integration/component/table/table-actionee.js
  src/analytics/script/integration/component/table/table-selector.js
  src/analytics/script/integration/component/tile/id.js
  src/analytics/script/integration/component/tile/tile-actionee.js
  src/analytics/script/integration/component/tile/tile-selector.js
  src/analytics/script/integration/component/transcription/id.js
  src/analytics/script/integration/component/transcription/transcription-actionee.js
  src/analytics/script/integration/component/transcription/transcription-button-actionee.js
  src/analytics/script/integration/component/transcription/transcription-selector.js
  src/component/badge/template/ejs/badge.ejs
  src/component/breadcrumb/template/ejs/breadcrumb.ejs
  src/component/notice/template/ejs/notice.ejs
  src/component/quote/template/ejs/quote.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/template/ejs/tile.ejs
Labels: ajout, en cours

#575 feat(api): ajoute une methode searchparams + config logs JS en prod [DS-2689]
  src/core/script/api/api.js
  src/core/script/api/internals.js
  src/core/script/api/options/options.js
  src/core/script/api/utilities/search-params/index.js
  tool/example/example.ejs
Labels: ajout
