Repository GouvernementFR/dsfr, pull requests merged in 2023-06, with the labels that each got.

#602 :sparkles: feat(tile): Ajout icone fleche, état désactivé, icone lien externe, tuile de téléchargement [DS-3243]
  src/component/card/example/deprecated/index.ejs
  src/component/card/example/download/index.ejs
  src/component/card/example/download/sample/sample-content.ejs
  src/component/card/example/download/sample/sample-horizontal.ejs
  src/component/card/example/download/sample/sample-img.ejs
  src/component/card/example/download/sample/sample-no-img.ejs
  src/component/card/example/download/sample/sample-sizes.ejs
  src/component/card/example/index.ejs
  src/component/card/i18n/fr.yml
  src/component/main.js
  src/component/tile/.package.yml
  src/component/tile/api.js
  src/component/tile/example/download/index.ejs
  src/component/tile/example/index.ejs
  src/component/tile/example/sample/sample-content.ejs
  src/component/tile/example/sample/sample-grid-horizontal.ejs
  src/component/tile/example/sample/sample-grid.ejs
  src/component/tile/example/sample/sample-horizontal.ejs
  src/component/tile/example/sample/sample-icon.ejs
  src/component/tile/example/sample/sample-no-img.ejs
  src/component/tile/example/sample/sample-sizes.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/i18n/fr.yml
  src/component/tile/index.js
  src/component/tile/index.scss
  src/component/tile/main.js
  src/component/tile/script/tile/tile-download.js
  src/component/tile/script/tile/tile-selector.js
  src/component/tile/style/_module.scss
  src/component/tile/style/_scheme.scss
  src/component/tile/style/_tool.scss
  src/component/tile/style/module/_default.scss
  src/component/tile/style/module/_download.scss
  src/component/tile/style/module/_sm.scss
  src/component/tile/style/module/_variations.scss
  src/component/tile/template/ejs/content.ejs
  src/component/tile/template/ejs/tile.ejs
Labels: évolution, Prêt, maj 1.9.3

#493 :sparkles: feat(name): ajout bouton de suppression de prénom [DS-2974]
  src/component/follow/style/_module.scss
  src/component/input/input-base/example/index.ejs
  src/component/input/input-base/example/sample/input-action.ejs
  src/component/input/input-base/i18n/fr.yml
  src/component/input/input-base/style/_module.scss
  src/component/input/input-base/style/_scheme.scss
  src/component/input/input-base/template/ejs/input.ejs
  src/pattern/name/example/data/js/add-firstname.js
  src/pattern/name/example/data/js/remove-firstname.js
  src/pattern/name/i18n/fr.yml
Labels: ajout, Prêt, maj 1.9.3

#531 :bug: fix(tab): écoute des événements de clavier déplacé sur la liste d'onglets [DS-2550]
  src/component/tab/index.js
  src/component/tab/script/tab/tab-emission.js
  src/component/tab/script/tab/tab-keys.js
  src/component/tab/script/tab/tabs-group.js
  src/component/tab/script/tab/tabs-list.js
  src/component/tab/style/module/_shadow.scss
Labels: correctif, Prêt, maj 1.9.3

#502 :recycle: refactor(radio,checkbox,toggle): passage input en bleu et refactorisation [DS-2897,DS-2899, DS-2182, DS-2778, DS-3048]
  module/color/mixin/_data-uri-svg.scss
  src/component/checkbox/deprecated/style/_module.scss
  src/component/checkbox/index.scss
  src/component/checkbox/legacy.scss
  src/component/checkbox/style/_legacy.scss
  src/component/checkbox/style/_module.scss
  src/component/checkbox/style/_scheme.scss
  src/component/checkbox/style/_tool.scss
  src/component/form/style/_scheme.scss
  src/component/radio/deprecated/style/_module.scss
  src/component/radio/style/_tool.scss
  src/component/radio/style/module/_default.scss
  src/component/radio/style/module/_rich.scss
  src/component/radio/style/module/_sm.scss
  src/component/radio/style/scheme/_default.scss
  src/component/radio/style/scheme/_rich.scss
  src/component/radio/style/scheme/_sm.scss
  src/component/toggle/example/index.ejs
  src/component/toggle/example/sample/toggle-group.ejs
  src/component/toggle/style/_legacy.scss
  src/component/toggle/style/_scheme.scss
  src/component/toggle/style/_setting.scss
  src/component/toggle/style/module/_default.scss
  src/component/toggle/style/module/_group.scss
  src/component/toggle/style/module/_variants.scss
  src/component/toggle/template/ejs/toggle.ejs
  src/core/style/action/setting/_elements.scss
Labels: correctif, évolution, Prêt, maj 1.9.3

#519 :bug: fix(core, modal): décalage scrollbar à l'ouverture/fermeture modale & fix scroll behavior [DS-3048,DS-3054]
  src/component/modal/style/_module.scss
  src/core/script/api/modules/scroll/scroll-locker.js
  src/core/style/display/module/_no-scroll.scss
Labels: correctif, Prêt, maj 1.9.3

#549 :sparkles: feat(pagination): évolution taille et écart des boutons [DS-2931]
  src/component/pagination/example/sample/pagination.ejs
  src/component/pagination/style/_module.scss
  src/component/pagination/style/_setting.scss
Labels: correctif, Prêt, maj 1.9.3

#609 :bug: fix(header, navigation): focus des nav-items mobile & ajustements [DS-3216]
  src/component/header/style/module/_nav.scss
  src/component/navigation/example/sample/navigation.ejs
  src/component/navigation/style/module/_default.scss
  src/component/navigation/style/module/_mega-menu.scss
  src/component/sidemenu/style/module/_list.scss
Labels: correctif, Prêt, maj 1.9.3

#615 :bug: fix(core): corrige liens pour retro-compat sur firefox [DS-3288]
  src/core/style/_outdated.scss
  src/core/style/action/tool/_link.scss
Labels: correctif, Prêt, maj 1.9.3

#622 :arrow_up: chore(dependencies): met a jour les dépendances Node [DS-3296]
  yarn.lock
Labels: dependencies, Prêt

#623 :pencil: doc(core): corrige les liens vers les pages de documentation des fondamentaux [DS-3298]
  README.md
  src/core/.package.yml
  src/utility/.folder.yml
  src/utility/icons/.folder.yml
  src/utility/icons/icons-buildings/.package.yml
  src/utility/icons/icons-business/.package.yml
  src/utility/icons/icons-communication/.package.yml
  src/utility/icons/icons-design/.package.yml
  src/utility/icons/icons-development/.package.yml
  src/utility/icons/icons-device/.package.yml
  src/utility/icons/icons-document/.package.yml
  src/utility/icons/icons-editor/.package.yml
  src/utility/icons/icons-finance/.package.yml
  src/utility/icons/icons-health/.package.yml
  src/utility/icons/icons-logo/.package.yml
  src/utility/icons/icons-map/.package.yml
  src/utility/icons/icons-media/.package.yml
  src/utility/icons/icons-others/.package.yml
  src/utility/icons/icons-system/.package.yml
  src/utility/icons/icons-user/.package.yml
  src/utility/icons/icons-weather/.package.yml
Labels: correctif, documentation, Prêt, maj 1.9.3

#540 ✨ feat(radio): radio rich sans images & pictogram à la place d'img [DS-1315]
  module/color/variable/_box-shadows.scss
  src/component/display/example/sample/body.ejs
  src/component/form/deprecated/style/_module.scss
  src/component/form/style/module/_fieldset.scss
  src/component/radio/deprecated/example/sample/radio-rich.ejs
  src/component/radio/deprecated/style/_module.scss
  src/component/radio/deprecated/style/_scheme.scss
  src/component/radio/example/index.ejs
  src/component/radio/example/sample/radios-rich.ejs
  src/component/radio/legacy.scss
  src/component/radio/main.scss
  src/component/radio/style/module/_default.scss
  src/component/radio/style/module/_rich.scss
  src/component/radio/style/scheme/_rich.scss
  src/component/radio/template/ejs/radio.ejs
  src/core/style/action/setting/_elements.scss
  src/core/style/artwork/_scheme.scss
Labels: évolution, maj 1.9.3, à vérifier

#613 :pencil: doc(core): ajoute des exemples liens bruts et resets [DS-2825]
  src/core/.package.yml
  src/core/example/link/index.ejs
  src/core/example/link/link-raw/index.ejs
  src/core/example/link/link-reset/index.ejs
  src/core/example/link/sample/blocks.ejs
  src/core/example/link/sample/library.ejs
  src/core/example/reset/index.ejs
  src/core/i18n/fr.yml
  src/core/style/action/legacy/_link.scss
  src/core/style/action/module/_link.scss
  src/core/style/action/tool/_link.scss
Labels: ajout, Prêt, maj 1.9.3

#621 :bug: fix(tab, core): correctif tab legacy & margin top des headings [DS-3281]
  src/component/tab/style/_legacy.scss
  src/core/style/typography/_legacy.scss
Labels: correctif, Prêt, maj 1.9.3

#564 🐛 fix(accordion, transcription, translate, sidemenu): Ajustement sur l'état défaut et actif [DS-3023, DS-3024, DS-3025, DS-3008, DS-3142, DS-3031, DS-3032]
  module/animate/_index.scss
  module/animate/mixin/_caret.scss
  src/component/accordion/style/_legacy.scss
  src/component/accordion/style/_module.scss
  src/component/accordion/style/_scheme.scss
  src/component/sidemenu/style/_scheme.scss
  src/component/transcription/style/_legacy.scss
  src/component/transcription/style/_module.scss
  src/component/transcription/style/_scheme.scss
  src/component/translate/style/_legacy.scss
  src/component/translate/style/_module.scss
Labels: correctif, Prêt, maj 1.9.3

#618 :bug: fix(account): met a jour la hiérarchie html des modèles de page [DS-3289, DS-3290]
  src/page/account/login/example/data/login.json.ejs
  src/page/account/recover/example/data/recover.json.ejs
  src/page/account/register/example/2-steps/2a-login/index.ejs
  src/page/account/register/example/data/address.json.ejs
  src/page/account/register/example/data/identity.json.ejs
  src/page/account/register/example/data/login.json.ejs
  src/page/account/template/ejs/blocks/colored.ejs
  src/page/account/template/ejs/blocks/heading.ejs
  src/page/account/template/ejs/segments/button.ejs
  src/page/account/template/ejs/segments/connect.ejs
  src/page/account/template/ejs/segments/heading.ejs
  src/page/account/template/ejs/segments/stepper.ejs
Labels: ajout, Prêt, maj 1.9.3

#624 ✨ feat(address): met a jour les message d'aide des champs de formulaire [DS-3295]
  src/component/form/style/module/_fieldset.scss
  src/component/input/input-email/i18n/fr.yml
  src/component/upload/i18n/fr.yml
  src/pattern/address/example/data/address.json.ejs
  src/pattern/address/i18n/fr.yml
  src/pattern/date/i18n/fr.yml
  src/pattern/name/i18n/fr.yml
Labels: ajout, à vérifier

#629 :bug: fix(share): correction copie url dans presse papier [DS-3309]
  src/component/share/example/sample/share-default.ejs
Labels: correctif, Prêt, maj 1.9.3

#625 :bug: fix(search): apparence du champ de recherche iOS
  src/core/style/action/module/_input.scss
Labels: correctif, Prêt, maj 1.9.3

#626 ✨ feat(analytic): ajoute le composant tooltip [DS-3234]
  src/analytics/.package.yml
  src/analytics/example/component/tooltip/index.ejs
  src/analytics/example/component/tooltip/tooltip-btn/index.ejs
  src/analytics/i18n/fr.yml
  src/analytics/script/integration/component/components.js
  src/analytics/script/integration/component/tooltip/id.js
  src/analytics/script/integration/component/tooltip/integrate.js
  src/analytics/script/integration/component/tooltip/tooltip-actionee.js
Labels: ajout, Prêt, maj 1.9.3

#631 :bug: fix(example): retire les attributs file des <link> [DS-3307]
  tool/example/style.ejs
Labels: ajout, Prêt, maj 1.9.3

#628 :bug: fix(tab): correction onglets imbriqués en legacy [DS-3313]
  src/analytics/script/integration/component/transcription/transcription-selector.js
  src/analytics/script/integration/component/translate/translate-selector.js
  src/component/accordion/script/accordion/accordion-selector.js
  src/component/accordion/script/accordion/accordions-group.js
  src/component/navigation/script/navigation/navigation-selector.js
  src/component/navigation/script/navigation/navigation.js
  src/component/sidemenu/script/sidemenu/sidemenu-list.js
  src/component/sidemenu/script/sidemenu/sidemenu-selector.js
  src/component/tab/script/tab/tab-panel.js
  src/component/tab/script/tab/tabs-group.js
  src/component/tab/style/_legacy.scss
  src/core/script/disclosure/disclosure.js
  src/core/script/disclosure/disclosures-group.js
Labels: correctif, Prêt, maj 1.9.3

#635 :sparkles: feat(select, input): ajout de la bordure en état erreur / succés / info [DS-3308]
  src/component/input/input-base/style/_module.scss
  src/component/input/input-base/style/_scheme.scss
  src/component/select/style/_module.scss
  src/component/select/style/_scheme.scss
Labels: évolution

#637 :bug: fix(header): duplication des id généralisée pour les quick access [DS-3306]
  src/component/header/script/header/header-links.js
Labels: correctif, Prêt, maj 1.9.3

#638 ⬆️ chore(dependencies): met a jour les dépendances Node [DS-3296]
  package.json
  yarn.lock
Labels: dependencies, Prêt, maj 1.9.3

#640 chore(*): changelog
  CHANGELOG.md
  package.json
  src/component/accordion/style/_module.scss
  src/component/accordion/style/_scheme.scss
  src/component/radio/deprecated/style/_module.scss
  src/component/radio/main.scss
  src/component/transcription/style/_scheme.scss
  src/core/example/link/sample/library.ejs
  src/core/style/_outdated.scss
  src/core/style/action/module/_link.scss
  src/core/style/typography/_legacy.scss
Labels: Prêt, maj 1.9.3
