Repository GouvernementFR/dsfr, pull requests merged in 2024-06, with the labels that each got.

#946 ✨ feat(icon): ajout d'icônes [DS-3466]
  src/core/icon/design/shapes-fill.svg
  src/core/icon/design/shapes-line.svg
  src/core/icon/logo/whatsapp-fill.svg
  src/core/icon/logo/whatsapp-line.svg
  src/core/icon/others/fr--accessibility-fill.svg
  src/core/icon/others/fr--accessibility-line.svg
  src/core/icon/others/fr--ear-off-fill.svg
  src/core/icon/others/fr--ear-off-line.svg
  src/core/icon/others/fr--mental-disabilities-fill.svg
  src/core/icon/others/fr--mental-disabilities-line.svg
  src/core/icon/others/fr--sign-language-fill.svg
  src/core/icon/others/fr--sign-language-line.svg
  src/core/icon/others/wheelchair-fill.svg
  src/core/icon/others/wheelchair-line.svg
  src/core/icon/system/arrow-right-up-line.svg
  src/core/icon/weather/fire-fill.svg
  src/core/icon/weather/fire-line.svg
  src/core/icon/weather/flood-fill.svg
  src/core/icon/weather/flood-line.svg
  src/core/icon/weather/fr--avalanches-fill.svg
  src/core/icon/weather/fr--submersion-fill.svg
  src/core/icon/weather/heavy-showers-line.svg
  src/core/icon/weather/snowy-fill.svg
  src/core/icon/weather/snowy-line.svg
  src/core/icon/weather/temp-cold-fill.svg
  src/core/icon/weather/temp-cold-line.svg
  src/core/icon/weather/thunderstorms-fill.svg
  src/core/icon/weather/thunderstorms-line.svg
  src/core/icon/weather/tornado-line.svg
  src/core/icon/weather/typhoon-line.svg
  src/core/icon/weather/windy-fill.svg
  src/core/icon/weather/windy-line.svg
Labels: ajout, Prêt, maj 1.11.2

#944 🐛 fix(footer, header): réduction de la zone de clic retour à l'accueil [DS-3800]
  src/component/footer/style/module/_default.scss
  src/component/header/style/_scheme.scss
  src/component/header/style/module/_brand.scss
  src/component/header/style/module/_navbar.scss
Labels: correctif, Prêt, maj 1.11.2

#943 🐛 fix(link, card, tile): enlarge button [DS-3798]
  src/component/card/example/index.ejs
  src/component/card/example/sample/sample-disabled.ejs
  src/component/card/style/_legacy.scss
  src/component/card/style/module/_content.scss
  src/component/card/style/module/_default.scss
  src/component/card/style/module/_download.scss
  src/component/card/style/module/_header.scss
  src/component/card/style/module/_lg.scss
  src/component/card/style/module/_sm.scss
  src/component/card/template/ejs/card.ejs
  src/component/card/template/ejs/content.ejs
  src/component/link/template/ejs/link.ejs
  src/component/tile/example/index.ejs
  src/component/tile/example/sample/sample-disabled.ejs
  src/component/tile/style/_legacy.scss
  src/component/tile/style/_scheme.scss
  src/component/tile/style/_tool.scss
  src/component/tile/style/module/_default.scss
  src/component/tile/style/module/_download.scss
  src/component/tile/style/module/_sm.scss
  src/component/tile/template/ejs/content.ejs
  src/component/tile/template/ejs/tile.ejs
  src/core/style/action/_module.scss
  src/core/style/action/legacy/_hover.scss
  src/core/style/action/module/_enlarge-link.scss
  src/core/style/action/module/_enlarge.scss
  src/core/template/ejs/action/action.ejs
Labels: correctif, Prêt, maj 1.11.2

#947 ✨ feat(table): ajoute le tableau non scrollable [DS-3742]
  module/legacy/mixin/_legacy.scss
  src/component/accordion/style/_module.scss
  src/component/button/style/module/_default.scss
  src/component/notice/style/_legacy.scss
  src/component/table/deprecated/style/_legacy.scss
  src/component/table/deprecated/style/module/_variants.scss
  src/component/table/example/data/data-lorem.json.ejs
  src/component/table/example/index.ejs
  src/component/table/i18n/fr.yml
  src/component/table/style/_legacy.scss
  src/component/table/style/module/_default.scss
  src/component/table/style/module/_variants.scss
  src/component/table/template/ejs/wrapper.ejs
  src/component/toggle/style/module/_default.scss
Labels: ajout, à vérifier, maj 1.11.2

#956 ✨ feat(icon): ajout icone weather/sparkling-2
  src/core/icon/weather/sparkling-2-fill.svg
  src/core/icon/weather/sparkling-2-line.svg
Labels: correctif, Prêt, maj 1.11.2

#954 🐛 fix(toggle): ajoute les messages erreur et valide sur interrupteur simple
  src/component/toggle/example/sample/toggle-default.ejs
  src/component/toggle/style/_scheme.scss
  src/component/toggle/style/module/_default.scss
  src/component/toggle/style/module/_group.scss
  src/component/toggle/template/ejs/toggle.ejs
Labels: correctif, Prêt, maj 1.11.2

#949 ✨ feat(table) : Mise à jour des exemples [DS-3742]
  src/component/table/.package.yml
  src/component/table/deprecated/style/_scheme.scss
  src/component/table/deprecated/style/module/_default.scss
  src/component/table/deprecated/style/module/_variants.scss
  src/component/table/example/data/data-complex-thead.json.ejs
  src/component/table/example/data/data-simple.json.ejs
  src/component/table/script/table/table-selector.js
  src/component/table/style/_legacy.scss
  src/component/table/style/_module.scss
  src/component/table/style/_scheme.scss
  src/component/table/style/module/_default.scss
  src/component/table/style/module/_shadow.scss
  src/component/tooltip/.package.yml
  src/component/tooltip/example/sample/tooltip-list.ejs
  src/component/tooltip/example/sample/tooltip-table.ejs
Labels: ajout, Prêt, maj 1.11.2

#952 🐛 fix(preference): correctifs mode contrasté et reduce motion [DS-3773]
  src/component/breadcrumb/style/_module.scss
  src/component/card/style/module/_content.scss
  src/component/connect/style/module/_group.scss
  src/component/consent/style/module/_services.scss
  src/component/form/deprecated/style/_module.scss
  src/component/modal/style/_module.scss
  src/component/radio/deprecated/style/_module.scss
  src/component/select/style/_module.scss
  src/component/summary/style/_module.scss
  src/core/style/display/tool/_hr.scss
Labels: correctif, Prêt, maj 1.11.2

#955 🐛 fix(IE): correctifs divers
  module/elevation/mixin/_drop.scss
  module/elevation/mixin/_elevate.scss
  module/elevation/mixin/_shadow.scss
  src/component/breadcrumb/style/_legacy.scss
  src/component/button/style/_legacy.scss
  src/component/navigation/style/module/_menu.scss
  src/component/navigation/style/scheme/_menu.scss
  src/component/password/style/_legacy.scss
  src/component/range/style/_legacy.scss
  src/component/skiplink/style/_legacy.scss
  src/component/summary/legacy.scss
  src/component/summary/style/_legacy.scss
  src/component/tag/style/_legacy.scss
  src/component/tag/style/_scheme.scss
  src/component/tooltip/style/_legacy.scss
  src/legacy/script/focus-within/focus-within-polyfill.min.js
  src/legacy/script/index.js
Labels: correctif, Prêt, maj 1.11.2

#962 🚀 chore(*): changelog v1.12.0
  CHANGELOG.md
  package.json
Labels: Prêt, maj 1.11.2

#972 🚀 chore(*): changelog v1.12.1
  CHANGELOG.md
  package.json
Labels: Prêt, maj 1.12.0
