Repository GouvernementFR/dsfr, pull requests merged in 2024-10, with the labels that each got.

#993 🐛 fix(core): Bug de récursivité infinie sur le getter node [DS-3841]
  src/core/script/api/modules/register/instance.js
Labels: correctif, Prêt, maj 1.12.1

#992 🐛 fix(modal): input sans type bug dans le focus trap de la modale [DS-3831]
  src/component/input/input-base/example/sample/inputs.ejs
  src/component/modal/example/sample/body/form.ejs
  src/component/modal/script/modal/focus-trap.js
Labels: correctif, Prêt, maj 1.12.1

#995 🐛 fix(analytics): lancement dsfr start dans les pages SPA [DS-3855]
  src/analytics/example/spa/angular/_index.ejs
  src/analytics/example/spa/react/index.ejs
  src/analytics/example/spa/vue/index.ejs
Labels: correctif, Prêt, maj 1.12.1

#996 🐛 fix(core): opacité du texte du select désactivé
  src/core/style/action/setting/_elements.scss
Labels: correctif, Prêt, maj 1.12.1

#997 ✨ fix(build): browsersync dependency >=2.27 [DS-3845]
  package.json
  yarn.lock
Labels: dependencies, Prêt, maj 1.12.1

#998 🐛 fix(anayltics): correction doc page.path [DS-3823]
  src/analytics/doc/analytics/collector/page.md
Labels: correctif, documentation, Prêt, maj 1.12.1

#1001 ✨ feat(pagination): retire lien sur les points de suspension
  src/component/pagination/example/sample/pagination.ejs
Labels: évolution, Prêt, maj 1.12.1

#1002 🐛 fix(readme): correction nom fichier utility [DS-3830]
  README.md
Labels: documentation, Prêt, maj 1.12.1

#1003 🐛 fix(notice): correction css markup hx sur le titre du bandeau [DS-3840]
  src/component/notice/style/_module.scss
Labels: correctif, Prêt, maj 1.12.1

#1004 ✨ feat(notice): icone alerte météo rouge [DS-3838]
  src/component/notice/style/_module.scss
Labels: évolution, Prêt, maj 1.12.1

#1005 🐛 fix(button): ajoute le type button par défaut [DS-3828]
  src/analytics/example/action/index.ejs
  src/analytics/example/spa/agnostic/index.ejs
  src/analytics/example/spa/agnostic/route.js.ejs
  src/analytics/example/spa/angular/_index.ejs
  src/analytics/example/spa/react/index.ejs
  src/analytics/example/spa/vue/index.ejs
  src/component/accordion/template/ejs/accordion.ejs
  src/component/alert/example/layout-dynamic.ejs
  src/component/breadcrumb/template/ejs/breadcrumb.ejs
  src/component/button/template/ejs/button.ejs
  src/component/card/template/ejs/content.ejs
  src/component/connect/example/data/connect.json.ejs
  src/component/connect/example/index.ejs
  src/component/connect/example/sample/connect-agent.ejs
  src/component/connect/example/sample/connect-plus.ejs
  src/component/connect/template/ejs/connect.ejs
  src/component/consent/template/ejs/manager.ejs
  src/component/display/deprecated/example/index.ejs
  src/component/follow/example/data/newsletter-form.json.ejs
  src/component/modal/example/sample/body/form.ejs
  src/component/navigation/template/ejs/btn.ejs
  src/component/sidemenu/template/ejs/btn.ejs
  src/component/sidemenu/template/ejs/sidemenu.ejs
  src/component/tab/template/ejs/tab.ejs
  src/component/tag/template/ejs/tag.ejs
  src/component/tile/template/ejs/content.ejs
  src/component/transcription/template/ejs/transcription.ejs
  src/page/account/login/example/data/login.json.ejs
  tool/example/controls.ejs
Labels: évolution, Prêt, maj 1.12.1

#1006 🐛 fix(toggle): correction groupe d'interrupteurs dépréciés [DS-3835]
  src/component/toggle/style/module/_group.scss
Labels: correctif, Prêt, maj 1.12.1

#1007 🐛 fix(link): alignement icone link close deprécié [DS-3837]
  src/component/link/deprecated/style/module/_close.scss
Labels: correctif, Prêt, maj 1.12.1

#1008 🐛 feat(sidemenu): correction focus sidemenu sticky [DS-3842]
  src/component/header/style/module/_brand.scss
  src/component/sidemenu/style/module/_action.scss
  src/component/sidemenu/style/module/_variants.scss
Labels: correctif, Prêt, maj 1.12.1

#1011 🐛 fix(range): amélioration du rendu en mode contrasté [DS-3808]
  src/component/range/style/_module.scss
Labels: correctif, Prêt, maj 1.12.1

#1019 🐛 fix(notice): padding notice sans close btn [DS-3848]
  src/component/notice/style/_module.scss
Labels: correctif, Prêt, maj 1.12.1

#1023 🐛 fix(core): bug firefox menu passe en arrière plan [DS-3852]
  src/core/style/collapse/_tool.scss
Labels: correctif, Prêt, maj 1.12.1

#1030 🐛 💥 fix(table): correction de l'attribut aria-sort [DS-3858]
  src/component/button/style/_legacy.scss
  src/component/button/style/module/_sort.scss
  src/component/table/example/data/data-miscellaneous.json.ejs
Labels: correctif, Prêt, maj 1.12.1

#976 :bug: fix(header): duplication aria-describedby & labelledby [DS-3827]
  src/component/header/script/header/header-links.js
Labels: correctif, Prêt, maj 1.12.1

#1000 🐛 fix(modal): correction modal footer z-index [DS-3839]
  src/component/modal/.package.yml
  src/component/modal/example/index.ejs
  src/component/modal/example/sample/body/table.ejs
  src/component/modal/style/_module.scss
Labels: correctif, Prêt, maj 1.12.1

#1010 🐛 fix(core, tooltip): positionnement du tooltip dans header & modale [DS-3733]
  src/component/tooltip/script/tooltip/tooltip-selector.js
  src/component/tooltip/script/tooltip/tooltip.js
  src/component/tooltip/style/_module.scss
  src/core/script/placement/placement.js
  src/core/style/placement/_module.scss
Labels: correctif, Prêt, maj 1.12.1

#1012 ✨ feat(api): ajouts d'évènements dans l'api [DS-2052]
  src/component/range/script/range/range-input.js
  src/component/range/script/range/range-input2.js
  src/core/script/action/toggle/toggle.js
  src/core/script/api/engine.js
  src/core/script/api/modules/register/Instance-event.js
  src/core/script/api/modules/register/instance.js
  src/core/script/api/modules/render/renderer.js
  src/core/script/api/modules/resize/resizer.js
  src/core/script/api/modules/scroll/scroll-locker.js
  src/core/script/api/modules/stage/root-event.js
  src/core/script/api/options/options.js
  src/core/script/api/utilities/dom/dispatch.js
  src/core/script/api/utilities/dom/index.js
  src/core/script/disclosure/disclosure-event.js
  src/core/script/disclosure/disclosure.js
  src/core/script/disclosure/disclosures-group.js
  src/scheme/script/scheme/scheme.js
Labels: correctif, Prêt, maj 1.12.1

#1032 🐛 fix(accordion): ouverture initiale des accordéons dégroupés [DS-3860]
  src/core/script/disclosure/disclosures-group.js
Labels: correctif, Prêt, maj 1.12.1

#1025 🐛 fix(range): ajout de la possibilité de changer la value en JS [DS-3853]
  src/component/range/script/range/range-input.js
  src/component/range/script/range/range-input2.js
Labels: correctif, Prêt, maj 1.12.1
