Repository GouvernementFR/dsfr, pull requests merged in 2024-05, with the labels that each got.

#932 🐛 fix(content): modifie la structure HTML du composant comportant une transcription [DS-3759]
  src/component/content/example/index.ejs
  src/component/content/example/sample/media-vid-default.ejs
  src/component/content/i18n/fr.yml
  src/component/content/style/_module.scss
  src/component/content/template/ejs/media.ejs
Labels: correctif, Prêt, maj 1.11.2

#931 🐛 fix(range): bug js boucle infinie et step désactivé [DS-3739, DS-3777]
  src/component/range/example/index.ejs
  src/component/range/example/sample/range.ejs
  src/component/range/i18n/fr.yml
  src/component/range/script/range/range-input.js
  src/component/range/script/range/range-input2.js
  src/component/range/script/range/range-model.js
  src/component/range/style/_scheme.scss
  src/component/range/template/ejs/range.ejs
Labels: correctif, Prêt, maj 1.11.2

#928 🐛 fix(toggle): retour à la ligne statut activé/désactivé [DS-3791]
  src/component/toggle/style/module/_default.scss
Labels: correctif, Prêt, maj 1.11.2

#918 ✨ feat(pictogram): ajout du picto digital/in-progress [DS-3792]
  src/core/asset/artwork/pictograms/digital/in-progress.svg
Labels: ajout, Prêt, maj 1.11.2

#912 🐛 fix(quote): ratio de l'image de citation [DS-3767]
  src/component/quote/style/_module.scss
Labels: correctif, Prêt, maj 1.11.2

#909 ✨ feat(build): ajoute le numéro de version dans les pages d'exemple [DS-1460]
  src/core/index.ejs
  tool/example/heading.ejs
Labels: évolution, Prêt, maj 1.11.2

#908 ✨ feat(build): ajoute la config au premier build & precision readme [DS-3681]
  README.md
  package.json
  tool/build/build.js
Labels: documentation, évolution, Prêt, maj 1.11.2

#905 🐛 fix(footer): title des liens obligatoires du footer [DS-3760, DS-3789]
  src/component/footer/example/sample/footer.ejs
  src/component/footer/template/ejs/content.ejs
  tool/example/decorator.ejs
Labels: correctif, Prêt, maj 1.11.2

#842 ✨ feat(card, tile, enlarge-link): ajoute version avec button [DS-3798]
  src/component/card/example/download/index.ejs
  src/component/card/example/download/sample/sample-button.ejs
  src/component/card/example/index.ejs
  src/component/card/example/sample/card-default.ejs
  src/component/card/example/sample/sample-button.ejs
  src/component/card/example/sample/sample-disabled.ejs
  src/component/card/style/_scheme.scss
  src/component/card/style/module/_content.scss
  src/component/card/style/module/_default.scss
  src/component/card/style/module/_lg.scss
  src/component/card/style/module/_sm.scss
  src/component/card/template/ejs/content.ejs
  src/component/link/example/download/index.ejs
  src/component/link/template/ejs/link.ejs
  src/component/tile/example/download/index.ejs
  src/component/tile/example/download/sample/sample-button.ejs
  src/component/tile/example/index.ejs
  src/component/tile/example/sample/sample-button.ejs
  src/component/tile/example/sample/sample-disabled.ejs
  src/component/tile/example/sample/tile-default.ejs
  src/component/tile/style/_scheme.scss
  src/component/tile/style/module/_default.scss
  src/component/tile/style/module/_sm.scss
  src/component/tile/template/ejs/content.ejs
  src/core/style/action/module/_enlarge-link.scss
Labels: évolution, Prêt, maj 1.11.2

#938 🐛 fix(card): fichier télécharger et ratio carte de téléchargement [DS-3580]
  src/component/card/example/download/sample/card-download.ejs
  src/component/card/example/sample/card-default.ejs
  tool/build/copy.js
  tool/example/img/placeholder-transcription.jpg
  tool/example/img/placeholder.16x9.png
  tool/example/img/placeholder.16x9.svg
  tool/example/img/placeholder.1x1.png
  tool/example/img/placeholder.1x1.svg
  tool/example/img/placeholder.2x3.png
  tool/example/img/placeholder.32x9.png
  tool/example/img/placeholder.3x2.png
  tool/example/img/placeholder.3x4.pdf
  tool/example/img/placeholder.3x4.png
  tool/example/img/placeholder.4x3.png
  tool/example/img/placeholder.9x16.png
  tool/example/img/placeholder.9x16.svg
  tool/example/img/placeholder.A4.png
  tool/example/img/placeholder.A4.svg
Labels: correctif, Prêt, maj 1.11.2

#937 ✨ feat(analytics): système de régulation des actions [DS-3799]
  src/analytics/doc/analytics.md
  src/analytics/doc/analytics/actions.md
  src/analytics/doc/analytics/collector/analytics.md
  src/analytics/example/action/index.ejs
  src/analytics/example/config.ejs
  src/analytics/i18n/fr.yml
  src/analytics/script/analytics/action/action-element.js
  src/analytics/script/analytics/action/action-regulation.js
  src/analytics/script/analytics/action/action.js
  src/analytics/script/analytics/engine/queue.js
  src/analytics/script/integration/core/actionee.js
Labels: évolution, Prêt, maj 1.11.2

#917 ✨ feat(notice): ajout de variations de bandeaux d'information importante [DS-3783, DS-3357]
  module/color/variable/_box-shadows.scss
  module/color/variable/_decisions.scss
  src/analytics/example/component/notice/index.ejs
  src/analytics/script/integration/component/components.js
  src/analytics/script/integration/component/notice/integrate.js
  src/analytics/script/integration/component/notice/notice-link-actionee.js
  src/analytics/script/integration/component/notice/notice-selector.js
  src/component/button/template/ejs/button.ejs
  src/component/form/example/index.ejs
  src/component/link/template/ejs/link.ejs
  src/component/notice/.package.yml
  src/component/notice/example/index.ejs
  src/component/notice/example/sample/sample-alert.ejs
  src/component/notice/example/sample/sample-content.ejs
  src/component/notice/example/sample/sample-generic.ejs
  src/component/notice/example/sample/sample-header.ejs
  src/component/notice/example/sample/sample-meteo.ejs
  src/component/notice/style/_legacy.scss
  src/component/notice/style/_module.scss
  src/component/notice/style/_scheme.scss
  src/component/notice/template/ejs/notice.ejs
  src/core/icon/system/fr--alert-warning-2-fill.svg
  src/core/icon/system/fr--alert-warning-fill.svg
  src/core/icon/weather/heavy-showers-fill.svg
  src/core/icon/weather/tornado-fill.svg
  src/core/icon/weather/typhoon-fill.svg
  src/core/template/ejs/action/action.ejs
Labels: évolution, Prêt, maj 1.11.2
