Repository GouvernementFR/dsfr, pull requests merged in 2024-11, with the labels that each got.

#1041 🐛 fix(table): bordure disparait lors d'un rowspan en dernière position [DS-3862]
  src/dsfr/component/table/style/_scheme.scss
  src/dsfr/component/table/style/module/_variants.scss
Labels: correctif, Prêt, maj 1.12.1

#1051 🐛 fix(tab): correction de l'ombre au scroll en RTL
  src/dsfr/component/tab/script/tab/tabs-list.js
Labels: correctif, Prêt, maj 1.12.1

#1049 🐛 fix(tile, navigation): retrait des sélecteur css ">"
  src/dsfr/component/navigation/style/module/_default.scss
  src/dsfr/component/navigation/style/module/_mega-menu.scss
  src/dsfr/component/navigation/style/module/_menu.scss
  src/dsfr/component/navigation/style/scheme/_menu.scss
  src/dsfr/component/tile/style/module/_default.scss
Labels: correctif, Prêt, maj 1.12.1

#1013 ✨ feat(colors) : page d'exemple utilitaires de couleurs [DS-2763]
  src/component/radio/style/module/_rich.scss
  src/component/radio/style/module/_sm.scss
  src/dsfr/utility/colors/.package.yml
  src/dsfr/utility/colors/_index.scss
  src/dsfr/utility/colors/_setting.scss
  src/dsfr/utility/colors/example/background/index.ejs
  src/dsfr/utility/colors/example/border/index.ejs
  src/dsfr/utility/colors/example/index.ejs
  src/dsfr/utility/colors/example/sample/default.ejs
  src/dsfr/utility/colors/example/text/index.ejs
  src/dsfr/utility/colors/i18n/fr.yml
  src/dsfr/utility/colors/mixin/_border.scss
  src/dsfr/utility/colors/mixin/_scheme.scss
  src/module/color/variable/_decisions.scss
  src/module/color/variable/_sets.scss
  tool/generate/colors.js
  tool/generate/config.js
Labels: ajout, Prêt, maj 1.12.1

#1053 feat(table): supporte le comportement `row-select` via data attribute
  src/dsfr/component/table/example/data/data-miscellaneous.json.ejs
  src/dsfr/component/table/example/data/data-simple.json.ejs
  src/dsfr/component/table/script/table/table-row.js
Labels: évolution, Prêt, maj 1.12.1

#1052 ⬆️ chore(dependencies): mise à jour des dépendances npm
  yarn.lock
Labels: dependencies, Prêt, maj 1.12.1

#1055 feat(analytics): optimisation des créations d'instances
  src/dsfr/analytics/doc/analytics/actions.md
  src/dsfr/analytics/doc/analytics/collector/analytics.md
  src/dsfr/analytics/example/reduce/config.ejs
  src/dsfr/analytics/example/reduce/index.ejs
  src/dsfr/analytics/i18n/fr.yml
  src/dsfr/analytics/main.js
  src/dsfr/analytics/script/analytics/engine/action-enable.js
  src/dsfr/analytics/script/analytics/engine/collector.js
  src/dsfr/analytics/script/analytics/engine/queue.js
  src/dsfr/analytics/script/integration/component/accordion/integrate.js
  src/dsfr/analytics/script/integration/component/alert/integrate.js
  src/dsfr/analytics/script/integration/component/badge/integrate.js
  src/dsfr/analytics/script/integration/component/breadcrumb/integrate.js
  src/dsfr/analytics/script/integration/component/button/integrate.js
  src/dsfr/analytics/script/integration/component/callout/integrate.js
  src/dsfr/analytics/script/integration/component/card/integrate.js
  src/dsfr/analytics/script/integration/component/checkbox/integrate.js
  src/dsfr/analytics/script/integration/component/components.js
  src/dsfr/analytics/script/integration/component/connect/integrate.js
  src/dsfr/analytics/script/integration/component/consent/integrate.js
  src/dsfr/analytics/script/integration/component/content/integrate.js
  src/dsfr/analytics/script/integration/component/download/integrate.js
  src/dsfr/analytics/script/integration/component/follow/integrate.js
  src/dsfr/analytics/script/integration/component/footer/integrate.js
  src/dsfr/analytics/script/integration/component/header/integrate.js
  src/dsfr/analytics/script/integration/component/highlight/integrate.js
  src/dsfr/analytics/script/integration/component/input/integrate.js
  src/dsfr/analytics/script/integration/component/link/integrate.js
  src/dsfr/analytics/script/integration/component/modal/integrate.js
  src/dsfr/analytics/script/integration/component/navigation/integrate.js
  src/dsfr/analytics/script/integration/component/notice/integrate.js
  src/dsfr/analytics/script/integration/component/pagination/integrate.js
  src/dsfr/analytics/script/integration/component/quote/integrate.js
  src/dsfr/analytics/script/integration/component/radio/integrate.js
  src/dsfr/analytics/script/integration/component/search/integrate.js
  src/dsfr/analytics/script/integration/component/select/integrate.js
  src/dsfr/analytics/script/integration/component/share/integrate.js
  src/dsfr/analytics/script/integration/component/sidemenu/integrate.js
  src/dsfr/analytics/script/integration/component/stepper/integrate.js
  src/dsfr/analytics/script/integration/component/summary/integrate.js
  src/dsfr/analytics/script/integration/component/tab/integrate.js
  src/dsfr/analytics/script/integration/component/table/integrate.js
  src/dsfr/analytics/script/integration/component/tag/integrate.js
  src/dsfr/analytics/script/integration/component/tile/integrate.js
  src/dsfr/analytics/script/integration/component/toggle/integrate.js
  src/dsfr/analytics/script/integration/component/tooltip/integrate.js
  src/dsfr/analytics/script/integration/component/transcription/integrate.js
  src/dsfr/analytics/script/integration/component/translate/integrate.js
  src/dsfr/analytics/script/integration/component/upload/integrate.js
  src/dsfr/analytics/script/integration/integration.js
  src/dsfr/analytics/script/integration/join-selector.js
  src/dsfr/component/accordion/template/ejs/accordion.ejs
Labels: évolution, Prêt, maj 1.12.1
