Repository GouvernementFR/dsfr, pull requests merged in 2024-03, with the labels that each got.

#881 🐛 fix(header): focus caché sur le lien du logo [DS-3723]
  src/component/header/style/module/_brand.scss
Labels: correctif, Prêt, maj 1.11.1

#885 🐛 fix(analytics): correctif héritage listenClick [DS-3745]
  src/analytics/script/integration/component/breadcrumb/breadcrumb-link-actionee.js
  src/analytics/script/integration/component/button/button-actionee.js
  src/analytics/script/integration/component/card/card-actionee.js
  src/analytics/script/integration/component/connect/connect-actionee.js
  src/analytics/script/integration/component/connect/connect-link-actionee.js
  src/analytics/script/integration/component/download/download-actionee.js
  src/analytics/script/integration/component/footer/footer-link-actionee.js
  src/analytics/script/integration/component/link/link-actionee.js
  src/analytics/script/integration/component/navigation/navigation-link-actionee.js
  src/analytics/script/integration/component/pagination/pagination-link-actionee.js
  src/analytics/script/integration/component/sidemenu/sidemenu-link-actionee.js
  src/analytics/script/integration/component/summary/summary-link-actionee.js
  src/analytics/script/integration/component/tag/tag-actionee.js
  src/analytics/script/integration/component/tile/tile-actionee.js
  src/analytics/script/integration/core/action/a-actionee.js
  src/analytics/script/integration/core/actionee.js
  src/core/script/api/modules/register/instance.js
Labels: correctif, Prêt, maj 1.11.1

#886 ✨ feat(core): ajout d'un retour à la ligne des mots trop long [DS-3737]
  src/core/style/reset/module/_body.scss
Labels: évolution, Prêt, maj 1.11.1

#887 🐛 fix(tag): corrige le hover des tags cliquables [DS-3724]
  src/component/tag/style/_scheme.scss
Labels: correctif, Prêt, maj 1.11.1

#888 ✨ feat(doc): ajout d'infos sur la configuration dans la doc analytics [DS-3741]
  src/analytics/doc/analytics/installation/configuration.md
Labels: évolution, Prêt, maj 1.11.1

#891 🐛 fix(range): correctif dispose input [DS-3748]
  src/component/range/script/range/range-input.js
Labels: correctif, Prêt, maj 1.11.1

#893 🐛 fix(header): correctif erreur itérable null [DS-3747]
  src/component/header/script/header/header-links.js
Labels: correctif, Prêt, maj 1.11.1

#894 ⬆️ chore(dependencies): met a jour la dépendance postCSS
  package.json
  yarn.lock
Labels: dependencies, Prêt, maj 1.11.1

#895 🐛 fix(analytics): documentation et correctif version standalone [DS-3746]
  src/analytics/doc/analytics.md
  src/analytics/doc/analytics/actions.md
  src/analytics/doc/analytics/collector.md
  src/analytics/doc/analytics/installation.md
  src/analytics/standalone/api.js
  src/analytics/standalone/config.js
  src/analytics/standalone/example/index.ejs
  src/core/script/api/api.js
  src/core/script/api/options/modes.js
  src/core/script/api/options/options.js
Labels: correctif, Prêt, maj 1.11.1
