Repository GouvernementFR/dsfr, pull requests merged in 2024-01, with the labels that each got.

#840 🐛 fix(navigation): corrige bugs de fermeture du composant [DS-3617, DS-3619]
  src/analytics/example/spa/agnostic/route.js.ejs
  src/analytics/script/integration/component/component-actionee.js
  src/analytics/script/integration/core/actionee.js
  src/component/header/script/header/header-modal.js
  src/component/navigation/script/navigation/navigation.js
Labels: correctif, Prêt, maj 1.11.0

#858 🐛 fix(follow): retrait d'un fichier inutile [DS-2165]
  src/component/follow/example/sample/data.ejs
Labels: correctif, Prêt, maj 1.11.0

#872 🐛 fix(footer, header, connect): retrait de l'icone target blank [DS-3715]
  src/component/connect/style/module/_default.scss
  src/component/footer/style/module/_default.scss
  src/component/footer/style/module/_partners.scss
  src/component/header/style/module/_brand.scss
Labels: correctif, Prêt, maj 1.11.0

#870 🐛 fix(select): corrige l'affichage du optgroup sur firefox windows [DS-3712]
  src/core/style/reset/_module.scss
  src/core/style/reset/module/_select.scss
Labels: correctif, Prêt, maj 1.11.0

#868 ✨ feat(analytics): ajout de la version du site [DS-3718]
  src/analytics/doc/analytics/collector/site.md
  src/analytics/example/config.ejs
  src/analytics/script/analytics/collector/site/site.js
Labels: évolution, Prêt, maj 1.11.0

#854 ✨ feat(recover): supprime le package recover et le deplace dans login [DS-3406]
  src/page/account/login/example/3-recover/3a-form/index.ejs
  src/page/account/login/example/3-recover/3b-confirmation/index.ejs
  src/page/account/login/example/3-recover/index.ejs
  src/page/account/login/example/data/recover.json.ejs
  src/page/account/login/example/sample/recover.ejs
  src/page/account/login/i18n/fr.yml
  src/page/account/recover/.package.yml
  src/page/account/recover/example/1-form/index.ejs
  src/page/account/recover/example/2-confirmation/index.ejs
  src/page/account/recover/i18n/fr.yml
Labels: ajout, Prêt, maj 1.11.0

#856 ✨ feat(header): retire aria attribut haspopup du burger menu en mobile [DS-3679]
  src/analytics/example/spa/agnostic/index.ejs
  src/analytics/example/spa/angular/_index.ejs
  src/analytics/example/spa/react/index.ejs
  src/analytics/example/spa/vue/index.ejs
  src/component/header/deprecated/template/ejs/navbar.ejs
  src/component/header/template/ejs/navbar.ejs
Labels: ajout, Prêt, maj 1.11.0

#864 🐛 fix(header): corrige le focus sur le champ de recherche [DS-3499]
  src/component/header/style/module/_modal.scss
Labels: correctif, Prêt, maj 1.11.0

#853 ✨ feat(alert): ajoute un example de taille md avec description seule [DS-3685, DS-3688]
  src/component/alert/example/index.ejs
Labels: ajout, Prêt, maj 1.11.0

#857 🐛 fix(pally): corrige les erreurs pally [DS-3579]
  src/analytics/example/component/summary/index.ejs
  src/analytics/example/spa/vue/index.ejs
  src/component/consent/example/index.ejs
  src/component/follow/example/data/newsletter-form.json.ejs
  src/component/search/template/ejs/search.ejs
  src/component/skiplink/example/prepend.ejs
  tool/test/pa11y.js
Labels: correctif, Prêt, maj 1.11.0

#866 ✨ feat(content): met a jour les mises en situation [DS-3365]
  src/component/content/example/index.ejs
  src/component/content/example/sample/media-default.ejs
  src/component/content/example/sample/media-img.ejs
  src/component/content/i18n/fr.yml
  src/component/transcription/i18n/fr.yml
  tool/example/img/placeholder-transcription.jpg
Labels: ajout, Prêt, maj 1.11.0

#846 🐛 fix(core): retrait du tap-highlight ios [DS-3719]
  src/component/checkbox/style/_module.scss
  src/component/radio/style/module/_default.scss
  src/component/segmented/style/module/_default.scss
  src/component/toggle/style/module/_default.scss
  src/core/style/reset/_module.scss
  src/core/style/reset/module/_tap-highlight.scss
Labels: correctif, Prêt, maj 1.11.0

#863 🐛 fix(tooltip): fallback du fond en conic gradiant [3628]
  src/component/tooltip/style/_scheme.scss
Labels: correctif, Prêt, maj 1.11.0

#859 🐛 fix(header): espacement des liens d'accès rapide en mobile [DS-3683]
  src/component/header/style/module/_links.scss
Labels: correctif, Prêt, maj 1.11.0

#860 ✨ feat(accordions-group): ajoute un attribut pour dégrouper [DS-3687]
  src/component/accordion/example/index.ejs
  src/component/accordion/example/sample/accordions-group.ejs
  src/component/accordion/template/ejs/accordions-group.ejs
  src/component/navigation/script/navigation/navigation.js
  src/core/script/collapse/collapses-group.js
  src/core/script/disclosure/disclosure-selector.js
  src/core/script/disclosure/disclosures-group.js
Labels: ajout, Prêt, maj 1.11.0

#876 🐛 fix(header): corrige les alignements des liens outils [DS-3683]
  src/component/header/example/index.ejs
  src/component/header/example/sample/header.ejs
  src/component/header/style/module/_links.scss
  src/component/header/template/ejs/tools.ejs
Labels: correctif, Prêt, maj 1.11.0

#877 ⬆️ chore(dependencies): met a jour les dépendances Node
  yarn.lock
Labels: Prêt, maj 1.11.0

#879 🚀 chore(*): changelog v1.11.1
  CHANGELOG.md
  package.json
Labels: Prêt, maj 1.11.0
