Repository GouvernementFR/dsfr, pull requests merged in 2025-05, with the labels that each got.

#1124 🐛 fix(fieldset): aligne les inputs inline
  src/dsfr/component/form/style/module/_fieldset.scss
Labels: correctif, Prêt, maj 1.13.1

#1129 🐛 fix(storybook): ajout bandeau alerte météo rouge dans le storybook
  src/dsfr/component/notice/template/stories/notice-arg-types.js
Labels: correctif, Prêt, maj 1.13.1

#1139 🐛 fix(core): enlarge link background hover
  src/dsfr/core/style/action/module/_enlarge.scss
Labels: correctif, Prêt, maj 1.13.1

#1140 🐛 fix(sidemenu, accordion): collapses ouverts au chargement [DSFR-96]
  src/dsfr/component/accordion/example/index.ejs
  src/dsfr/component/accordion/example/sample/accordions-group.ejs
  src/dsfr/component/accordion/template/ejs/accordion.ejs
  src/dsfr/component/sidemenu/example/sample/sidemenu.ejs
  src/dsfr/component/sidemenu/template/ejs/sidemenu-menu.ejs
Labels: correctif, à valider, maj 1.13.1

#1141 📝 docs(readme): Typo dans le README `utility.scss` => `utility.css`
  README.md
Labels: documentation, Prêt

#1142 📝 docs(analytics): links fix [DSFR-99]
  src/dsfr/analytics/doc/analytics/collector/user.md
  src/dsfr/analytics/doc/analytics/installation/configuration.md
Labels: correctif, documentation, Prêt, maj 1.13.2

#1143 🐛 fix(storybook): propriété type du bouton et retrait blocage scroll modal [DSFR-85]
  dsfr-sb/.storybook/preview.css
  src/dsfr/component/button/template/ejs/button.ejs
  src/dsfr/component/button/template/stories/button-arg-types.js
  src/dsfr/core/template/ejs/action/action.ejs
Labels: correctif, à vérifier, maj 1.13.1

#1154 🐛 fix(modal): correction warning header
  src/dsfr/component/header/script/header/header-modal.js
  src/dsfr/component/modal/script/modal/modal.js
Labels: correctif, Prêt, maj 1.13.1

#1144 ✨ feat(analytics): ajout proxy méthode actionee act() [DSFR-95]
  src/dsfr/analytics/script/integration/core/actionee.js
Labels: évolution, Prêt, maj 1.13.1

#1156 ⬆️ chore(dependencies): mise à jour des dépendances npm
  .github/workflows/notify.yml
  dsfr-sb/yarn.lock
  yarn.lock
Labels: dependencies, Prêt, maj 1.13.1
