Repository GouvernementFR/dsfr, pull requests merged in 2025-08, with the labels that each got.

#1259 docs: faute d'orthographe
  src/dsfr/layout/pattern/forms/_part/doc/index.md
Labels: documentation, Prêt, maj 1.14

#1274 :bug: fix(toggle): retrait css non conforme dans le fichier print
  src/dsfr/component/toggle/style/_print.scss
Labels: correctif, Prêt, maj 1.14

#1277 📝 docs: correction mineures documentation
  src/dsfr/component/button/_part/doc/code/index.md
  src/dsfr/component/display/_part/doc/code/index.md
  src/dsfr/component/footer/_part/doc/code/index.md
  src/dsfr/component/link/_part/doc/code/index.md
  src/dsfr/component/tooltip/_part/doc/code/index.md
  src/dsfr/layout/pattern/forms/_part/doc/index.md
Labels: documentation, Prêt, maj 1.14

#1254 ⬆️ chore(dependencies): mise à jour des dépendances npm
  yarn.lock
Labels: dependencies, maj 1.14

#1252 ⬆️ chore(Node): Change la version minimale de Node.js
  package.json
Labels: évolution, maj 1.14

#1279 🐛 fix(build): correction du build des exemples
  src/dsfr/component/table/example/data/data-simple.json.ejs
Labels: correctif, Prêt, maj 1.14
