Repository GouvernementFR/dsfr, pull requests merged in 2025-07, with the labels that each got.

#1222 🐛 fix: correction exemple lien externe [DSFR-112]
  src/dsfr/component/link/deprecated/template/ejs/link.ejs
  src/dsfr/component/link/example/index.ejs
Labels: correctif, Prêt, maj 1.14

#1213 🐛 fix(tooltip): placement du focus a la fermeture clavier
  src/dsfr/component/tooltip/script/tooltip/tooltip-referent.js
Labels: correctif, Prêt, maj 1.14

#1243 ✨ fix(analytics): retrait du patch pour les versions inférieures à 1.9
  src/dsfr/analytics/_part/doc/code/index.md
  src/dsfr/analytics/script/analytics/analytics.js
  src/dsfr/patch/.package.yml
  src/dsfr/patch/main.js
  src/dsfr/patch/script/internals.js
  src/dsfr/patch/script/patch.js
Labels: évolution, Prêt, maj 1.14

#1229 🐛 fix(translate): modification du markup nav en div [DSFR-108]
  src/dsfr/component/translate/_part/doc/accessibility/index.md
  src/dsfr/component/translate/_part/doc/code/index.md
  src/dsfr/component/translate/example/sample/translate-default.ejs
  src/dsfr/component/translate/template/ejs/translate.ejs
Labels: ajout, à valider, maj 1.14

#1228 🐛 fix(storybook): applique la gestion du thème dsfr sur les iframes storybook
  dsfr-sb/.storybook/dsfr-theme.js
Labels: correctif, à valider, maj 1.14

#1225 ✨ fix(toggle): retrait de l'interrupteur avec libellé à gauche et amélioration de la doc [DSFR-111]
  src/dsfr/component/toggle/_part/doc/accessibility/index.md
  src/dsfr/component/toggle/_part/doc/code/index.md
  src/dsfr/component/toggle/_part/doc/design/index.md
  src/dsfr/component/toggle/_part/doc/index.md
  src/dsfr/component/toggle/deprecated/example/index.ejs
  src/dsfr/component/toggle/example/index.ejs
  src/dsfr/component/toggle/template/stories/toggle-arg-types.js
  src/dsfr/component/toggle/template/stories/toggle.stories.js
  src/dsfr/component/toggle/template/stories/toggles-group-arg-types.js
  src/dsfr/component/toggle/template/stories/toggles-group.stories.js
Labels: évolution, à valider, maj 1.14

#1221 🐛 fix(modal): marges de la modale en pourcentage
  dsfr-sb/.storybook/preview.css
  src/dsfr/component/display/template/stories/display.stories.js
  src/dsfr/component/modal/script/modal/focus-trap.js
  src/dsfr/component/modal/script/modal/modal-body.js
  src/dsfr/component/modal/style/_module.scss
Labels: correctif, à vérifier, maj 1.14

#1214 🐛 fix(navigation): correction bordure navigation mobile avec 1 seul item
  src/dsfr/component/navigation/style/module/_default.scss
  src/dsfr/component/navigation/style/scheme/_default.scss
Labels: correctif, à vérifier, maj 1.14

#1210 feat(artworks): ajout pictogrammes manquants
  src/dsfr/core/asset/artwork/pictograms/accessibility/ear-off.svg
  src/dsfr/core/asset/artwork/pictograms/accessibility/eye-off.svg
  src/dsfr/core/asset/artwork/pictograms/accessibility/mental-disabilities.svg
  src/dsfr/core/asset/artwork/pictograms/accessibility/wheelchair.svg
  src/dsfr/core/asset/artwork/pictograms/buildings/base.svg
  src/dsfr/core/asset/artwork/pictograms/buildings/companie.svg
  src/dsfr/core/asset/artwork/pictograms/digital/smartphone.svg
  src/dsfr/core/asset/artwork/pictograms/document/archive.svg
  src/dsfr/core/asset/artwork/pictograms/document/binders.svg
  src/dsfr/core/asset/artwork/pictograms/document/conclusion.svg
  src/dsfr/core/asset/artwork/pictograms/document/document-search.svg
  src/dsfr/core/asset/artwork/pictograms/document/driving-license-new.svg
  src/dsfr/core/asset/artwork/pictograms/document/international-driving-license-new.svg
  src/dsfr/core/asset/artwork/pictograms/document/international-driving-license.svg
  src/dsfr/core/asset/artwork/pictograms/document/national-identity-card-passport.svg
  src/dsfr/core/asset/artwork/pictograms/document/presse-card.svg
  src/dsfr/core/asset/artwork/pictograms/document/sign-document.svg
  src/dsfr/core/asset/artwork/pictograms/health/doctor.svg
  src/dsfr/core/asset/artwork/pictograms/health/medical-research.svg
  src/dsfr/core/asset/artwork/pictograms/institutions/army-tank.svg
  src/dsfr/core/asset/artwork/pictograms/institutions/astronaut.svg
  src/dsfr/core/asset/artwork/pictograms/institutions/navy-anchor.svg
  src/dsfr/core/asset/artwork/pictograms/institutions/navy-bachi.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/audio.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/catalog.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/pictures.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/podcast.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/video-games.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/video.svg
  src/dsfr/core/asset/artwork/pictograms/map/backpack.svg
  src/dsfr/core/asset/artwork/pictograms/map/compass.svg
  src/dsfr/core/asset/artwork/pictograms/map/location-overseas-france.svg
  src/dsfr/core/asset/artwork/pictograms/map/map-pin.svg
  src/dsfr/core/asset/artwork/pictograms/map/travel-back.svg
  src/dsfr/core/asset/artwork/pictograms/system/flow-list.svg
  src/dsfr/core/asset/artwork/pictograms/system/flow-settings.svg
  src/dsfr/core/asset/artwork/pictograms/system/language.svg
Labels: ajout, Prêt, maj 1.14
