Repository GouvernementFR/dsfr, pull requests merged in 2025-06, with the labels that each got.

#1194 fix(storybook): corrige affichage des stories modales et autres iframes
  dsfr-sb/.storybook/preview.css
  src/dsfr/component/card/_part/doc/design/index.md
  src/dsfr/component/card/template/stories/card.stories.js
  src/dsfr/component/input/_part/doc/design/index.md
  src/dsfr/component/segmented/_part/doc/design/index.md
  src/dsfr/component/select/_part/doc/design/index.md
  src/dsfr/component/select/_part/doc/index.md
  src/dsfr/component/skiplink/_part/doc/index.md
  src/dsfr/component/summary/_part/doc/index.md
Labels: correctif

#1198 feat(components): ajoute attribut titleId
  src/dsfr/component/accordion/_part/doc/index.md
  src/dsfr/component/alert/_part/doc/index.md
  src/dsfr/component/badge/_part/doc/index.md
  src/dsfr/component/breadcrumb/_part/doc/index.md
  src/dsfr/component/button/_part/doc/index.md
  src/dsfr/component/callout/_part/doc/index.md
  src/dsfr/component/card/_part/doc/index.md
  src/dsfr/component/checkbox/_part/doc/index.md
  src/dsfr/component/combobox/_part/doc/index.md
  src/dsfr/component/composition/_part/doc/index.md
  src/dsfr/component/connect/_part/doc/index.md
  src/dsfr/component/consent/_part/doc/index.md
  src/dsfr/component/content/_part/doc/index.md
  src/dsfr/component/display/_part/doc/index.md
  src/dsfr/component/download/_part/doc/index.md
  src/dsfr/component/dropdown/_part/doc/index.md
  src/dsfr/component/follow/_part/doc/index.md
  src/dsfr/component/footer/_part/doc/index.md
  src/dsfr/component/form/_part/doc/index.md
  src/dsfr/component/header/_part/doc/index.md
  src/dsfr/component/highlight/_part/doc/index.md
  src/dsfr/component/input/_part/doc/index.md
  src/dsfr/component/link/_part/doc/index.md
  src/dsfr/component/logo/_part/doc/index.md
  src/dsfr/component/modal/_part/doc/index.md
  src/dsfr/component/navigation/_part/doc/index.md
  src/dsfr/component/notice/_part/doc/index.md
  src/dsfr/component/pagination/_part/doc/index.md
  src/dsfr/component/password/_part/doc/index.md
  src/dsfr/component/quote/_part/doc/index.md
  src/dsfr/component/radio/_part/doc/index.md
  src/dsfr/component/range/_part/doc/index.md
  src/dsfr/component/search/_part/doc/index.md
  src/dsfr/component/segmented/_part/doc/index.md
  src/dsfr/component/select/_part/doc/index.md
  src/dsfr/component/share/_part/doc/index.md
  src/dsfr/component/sidemenu/_part/doc/index.md
  src/dsfr/component/skiplink/_part/doc/index.md
  src/dsfr/component/stepper/_part/doc/index.md
  src/dsfr/component/summary/_part/doc/index.md
  src/dsfr/component/tab/_part/doc/index.md
  src/dsfr/component/table/_part/doc/index.md
  src/dsfr/component/tabnav/_part/doc/index.md
  src/dsfr/component/tag/_part/doc/index.md
  src/dsfr/component/tile/_part/doc/index.md
  src/dsfr/component/toggle/_part/doc/index.md
  src/dsfr/component/tooltip/_part/doc/index.md
  src/dsfr/component/transcription/_part/doc/index.md
  src/dsfr/component/translate/_part/doc/index.md
  src/dsfr/component/upload/_part/doc/index.md
  src/dsfr/component/user/_part/doc/index.md
Labels: ajout, à vérifier, maj 1.13.2

#1174 ✨ feat(modal, tooltip): ajoute une condition a la fermeture de la modale
  src/dsfr/component/modal/.package.yml
  src/dsfr/component/modal/example/index.ejs
  src/dsfr/component/modal/example/sample/body/table.ejs
  src/dsfr/component/modal/script/modal/modal.js
Labels: ajout, à vérifier, maj 1.13.2

#1160 ✨ feat(artworks): ajoute nouveaux pictogrammes [DSFR-105]
  src/dsfr/core/asset/artwork/pictograms/accessibility/accessibility.svg
  src/dsfr/core/asset/artwork/pictograms/digital/ecosystem.svg
  src/dsfr/core/asset/artwork/pictograms/digital/innovation.svg
  src/dsfr/core/asset/artwork/pictograms/digital/self-training.svg
  src/dsfr/core/asset/artwork/pictograms/leisure/art.svg
  src/dsfr/utility/pictograms/pictograms-accessibility/.package.yml
  src/dsfr/utility/pictograms/pictograms-accessibility/example/index.ejs
Labels: ajout, Prêt, maj 1.13.2

#1205 🐛 fix: chemin des styles standalone
  src/dsfr/layout/page/response/unavailable/standalone/main.scss
  src/dsfr/layout/page/response/unavailable/standalone/style/_module.scss
Labels: correctif
