Repository GouvernementFR/dsfr, pull requests merged in 2025-03, with the labels that each got.

#1079 ✨ feat(storybook): ajout de la page docs storybook du modal consent
  dsfr-sb/.storybook/preview.css
  src/dsfr/component/consent/template/stories/consent-modal.stories.js
Labels: ajout, à vérifier, maj 1.13.0

#1075 🐛 fix(storybook): corrige tooltip [DSFR-53]
  src/dsfr/component/tooltip/template/stories/tooltip.stories.js
Labels: correctif, à vérifier, à valider, maj 1.13.0

#1100 🐛 fix(storybook): nom du type de bandeau attentat dans le storybook
  src/dsfr/component/notice/template/ejs/notice.ejs
  src/dsfr/component/notice/template/stories/notice-arg-types.js
Labels: correctif, à valider, maj 1.13.0

#1096 ✨ feat(icon, share, follow): ajout icone Bluesky [DSFR-72]
  src/dsfr/component/follow/example/data/socials.json.ejs
  src/dsfr/component/follow/style/_setting.scss
  src/dsfr/component/follow/template/stories/follow-arg-types.js
  src/dsfr/component/share/example/data/share.json.ejs
  src/dsfr/component/share/style/_setting.scss
  src/dsfr/component/share/template/ejs/share.ejs
  src/dsfr/component/share/template/stories/share-arg-types.js
  src/dsfr/core/icon/logo/bluesky-fill.svg
  src/dsfr/core/icon/logo/bluesky-line.svg
Labels: ajout, Prêt, maj 1.13.0

#1092 🐛 fix(core): disclosure evenement dsfr.conceal [DSFR-71]
  src/dsfr/component/accordion/example/sample/accordions-group.ejs
  src/dsfr/core/script/disclosure/disclosure.js
Labels: correctif, Prêt, maj 1.13.0

#1090 🐛 fix(select): correction option par défaut & navigation clavier [DSFR-63]
  src/dsfr/component/select/template/ejs/select.ejs
Labels: correctif, Prêt, maj 1.13.0

#1088 ✨ build(release): retrait de storybook dans la release [DSFR-58]
  package.json
Labels: évolution, Prêt, maj 1.13.0

#1076 🐛 fix(input): focus date-picker [DSFR-54]
  src/dsfr/component/input/input-base/style/_module.scss
  src/dsfr/component/input/input-base/style/_scheme.scss
Labels: correctif, Prêt, maj 1.13.0

#1110 ✨ feat(icon): ajouts d'icônes d'éditeur et de partage
  src/dsfr/core/icon/design/eraser-fill.svg
  src/dsfr/core/icon/design/eraser-line.svg
  src/dsfr/core/icon/editor/align-center.svg
  src/dsfr/core/icon/editor/align-justify.svg
  src/dsfr/core/icon/editor/align-left.svg
  src/dsfr/core/icon/editor/align-right.svg
  src/dsfr/core/icon/editor/code-block.svg
  src/dsfr/core/icon/editor/font-color.svg
  src/dsfr/core/icon/editor/format-clear.svg
  src/dsfr/core/icon/editor/indent-decrease.svg
  src/dsfr/core/icon/editor/indent-increase.svg
  src/dsfr/core/icon/editor/list-check.svg
  src/dsfr/core/icon/editor/strikethrough.svg
  src/dsfr/core/icon/editor/text-direction-r.svg
  src/dsfr/core/icon/editor/underline.svg
  src/dsfr/core/icon/media/align-left.svg
  src/dsfr/core/icon/system/share-fill.svg
  src/dsfr/core/icon/system/share-forward-fill.svg
  src/dsfr/core/icon/system/share-forward-line.svg
  src/dsfr/core/icon/system/share-line.svg
Labels: ajout, Prêt, maj 1.13.0

#1103 🐛 fix(modal): bouton non requis + correctif [DSFR-17, DSFR-26]
  src/dsfr/component/button/template/stories/button-arg-types.js
  src/dsfr/component/button/template/stories/button.js
  src/dsfr/component/header/script/header/header-modal.js
  src/dsfr/component/header/script/header/header-selector.js
  src/dsfr/component/modal/example/index.ejs
  src/dsfr/component/modal/example/sample/modal-default.ejs
  src/dsfr/component/modal/script/modal/modal-body.js
  src/dsfr/component/modal/script/modal/modal.js
  src/dsfr/component/modal/template/ejs/button.ejs
  src/dsfr/core/script/api/modules/register/focus-manager.js
  src/dsfr/core/script/api/modules/register/instance.js
  src/dsfr/core/script/disclosure/disclosure-type.js
  src/dsfr/core/script/disclosure/disclosure.js
  src/dsfr/core/script/disclosure/disclosures-group.js
Labels: correctif, Prêt, maj 1.13.0

#1115 🐛 fix(publicode): corrige l'image du logo dsfr [DSFR-75]
  publiccode.yml
Labels: correctif, Prêt, maj 1.13.0

#1058 🐛 fix(tag): bug hover tags sélectionnables désactivés
  src/dsfr/component/tag/style/_scheme.scss
Labels: correctif, Prêt, maj 1.13.0

#1095 ✨ feat(core): assess file error detection [DSFR-28]
  src/dsfr/core/script/assess/assess-file.js
Labels: évolution, Prêt, maj 1.13.0

#1089 🐛 fix(storybook): Ajouts et corrections de stories [DSFR-69, DSFR-70]
  dsfr-sb/.storybook/preview.css
  src/dsfr/component/alert/template/stories/alert.stories.js
  src/dsfr/component/badge/template/stories/badge.stories.js
  src/dsfr/component/badge/template/stories/badges-group.stories.js
  src/dsfr/component/button/template/stories/button.stories.js
  src/dsfr/component/button/template/stories/buttons-group.stories.js
  src/dsfr/component/callout/template/stories/callout.stories.js
  src/dsfr/component/card/template/stories/card.stories.js
  src/dsfr/component/checkbox/template/stories/checkbox.stories.js
  src/dsfr/component/checkbox/template/stories/checkboxes-group.stories.js
  src/dsfr/component/connect/template/stories/connect.stories.js
  src/dsfr/component/consent/template/stories/consent-modal.stories.js
  src/dsfr/component/content/template/stories/content.stories.js
  src/dsfr/component/follow/template/stories/follow.stories.js
  src/dsfr/component/form/style/module/_fieldset.scss
  src/dsfr/component/form/template/stories/form-arg-types.js
  src/dsfr/component/form/template/stories/form.stories.js
  src/dsfr/component/form/template/stories/message.js
  src/dsfr/component/header/template/stories/header.stories.js
  src/dsfr/component/highlight/template/stories/highlight.stories.js
  src/dsfr/component/input/input-base/template/stories/input.stories.js
  src/dsfr/component/input/input-base/template/stories/inputs-group-arg-types.js
  src/dsfr/component/input/input-base/template/stories/inputs-group.stories.js
  src/dsfr/component/link/template/stories/links-group.stories.js
  src/dsfr/component/logo/template/stories/logo.stories.js
  src/dsfr/component/modal/template/stories/modal-arg-types.js
  src/dsfr/component/modal/template/stories/modal.stories.js
  src/dsfr/component/navigation/template/stories/navigation.stories.js
  src/dsfr/component/notice/template/ejs/notice.ejs
  src/dsfr/component/notice/template/stories/notice-arg-types.js
  src/dsfr/component/notice/template/stories/notice.stories.js
  src/dsfr/component/password/template/stories/password.stories.js
  src/dsfr/component/quote/template/stories/quote.stories.js
  src/dsfr/component/radio/template/stories/radios-group.stories.js
  src/dsfr/component/search/template/stories/search.stories.js
  src/dsfr/component/segmented/template/stories/segmented.stories.js
  src/dsfr/component/select/template/stories/select.stories.js
  src/dsfr/component/share/template/stories/share.stories.js
  src/dsfr/component/table/template/stories/table.stories.js
  src/dsfr/component/tag/template/stories/tag.stories.js
  src/dsfr/component/tag/template/stories/tags-group.stories.js
  src/dsfr/component/tile/template/stories/tile-arg-types.js
  src/dsfr/component/tile/template/stories/tile.stories.js
  src/dsfr/component/toggle/template/stories/toggle-group.stories.js
  src/dsfr/component/toggle/template/stories/toggle.stories.js
  src/dsfr/component/toggle/template/stories/toggles-group-arg-types.js
  src/dsfr/component/toggle/template/stories/toggles-group.stories.js
  src/dsfr/component/tooltip/template/stories/tooltip.stories.js
  src/dsfr/component/translate/template/stories/translate-arg-types.js
  src/dsfr/component/translate/template/stories/translate.stories.js
  src/dsfr/component/upload/template/ejs/upload.ejs
  src/dsfr/component/upload/template/stories/upload-arg-types.js
  src/dsfr/component/upload/template/stories/upload.stories.js
Labels: correctif, évolution, Prêt, maj 1.13.0

#1118 ✨ feat(package.json): ajout des fichiers markdown et publiccode
  package.json
Labels: Prêt

#1119 🐛 fix: lint & es5 export
  src/dsfr/component/toggle/template/stories/toggle.stories.js
  src/dsfr/core/script/api/modules/register/focus-manager.js
Labels: correctif, Prêt
